Repository intlify/vue-i18n, pull requests merged in 2020-12, with the labels that each got.

#204 breaking: change globalInjection default disable
  docs-old/.vuepress/config.js
  docs/advanced/composition.md
  docs/api/injection.md
  examples/composition/formatting/linked.html
  examples/composition/scope/global.html
  src/i18n.ts
  src/vue.d.ts
Labels: Type: Breaking

#206 feat: resources merge to global scope
  docs/advanced/composition.md
  docs/advanced/sfc.md
  docs/migration/features.md
  src/composer.ts
  src/i18n.ts
  test/i18n.test.ts
Labels: Type: Feature

#211 fix: cannot resolve deps in webpack
  package.json
  rollup.config.js
  yarn.lock
Labels: Type: Bug

#226 fix i18n interface typing for app.use
  packages/vue-i18n/src/i18n.ts
Labels: Type: Bug

#227 remove browser field
  packages/core/package.json
  packages/message-compiler/package.json
  packages/vue-i18n/package.json
Labels: Type: Improvement

#228 docs: fix various typos
  docs/advanced/optimization.md
  docs/api/injection.md
  docs/installation.md
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Documentation

#231 improvement: export more type definitions
  packages/core/src/context.ts
  packages/message-compiler/src/compiler.ts
  packages/message-compiler/src/errors.ts
  packages/message-compiler/src/generator.ts
  packages/message-compiler/src/parser.ts
Labels: Type: Improvement

#235 improvement: inline code generation
  packages/core-base/package.json
  packages/core/package.json
  packages/message-compiler/package.json
  packages/message-compiler/src/generator.ts
  packages/message-compiler/src/options.ts
  packages/message-compiler/test/__snapshots__/compiler.test.ts.snap
  packages/message-compiler/test/__snapshots__/generator.test.ts.snap
  packages/message-compiler/test/compiler.test.ts
  packages/message-compiler/test/generator.test.ts
  packages/runtime/package.json
  packages/vue-i18n/package.json
Labels: Type: Improvement

#237 improvement: api exporting
  format-explorer/webpack.config.js
  packages/core-base/src/compile.ts
  packages/core-base/src/context.ts
  packages/core-base/src/datetime.ts
  packages/core-base/src/errors.ts
  packages/core-base/src/number.ts
  packages/core-base/src/translate.ts
  packages/core-base/src/warnings.ts
  packages/message-compiler/src/errors.ts
  packages/shared/src/index.ts
  packages/vue-i18n/src/composer.ts
Labels: Type: Improvement

#238 tweak runtime warning
  packages/core-base/src/translate.ts
Labels: Type: Improvement

#242 Fix not to get loc when passing true to ParserOptions.location
  packages/message-compiler/src/parser.ts
  packages/message-compiler/src/tokenizer.ts
Labels: Type: Bug

#243 Fix maybe typo
  packages/message-compiler/src/generator.ts
  packages/message-compiler/src/parser.ts
Labels: Type: Bug

#245 improvement(message-compiler): Change to generate AST with linked message error
  packages/message-compiler/src/parser.ts
  packages/message-compiler/test/__snapshots__/parser.test.ts.snap
  packages/message-compiler/test/parser.test.ts
Labels: Type: Improvement

#246 breaking: change sfc custom block interface
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/test/composer.test.ts
  packages/vue-i18n/test/i18n.test.ts
  packages/vue-i18n/test/mixin.test.ts
Labels: Type: Breaking

#247 change vue-i18n and core es module for bundler
  docs/essentials/fallback.md
  docs/essentials/local.md
  e2e/fallback/basic.test.js
  e2e/fallback/default-format.test.js
  e2e/fallback/format.test.js
  e2e/fallback/option.test.js
  e2e/fallback/suppress.test.js
  e2e/missing/handler.test.js
  e2e/missing/option.test.js
  e2e/missing/suppress.test.js
  jest.config.js
  packages/core-base/package.json
  packages/core-base/src/translate.ts
  packages/core/package.json
  packages/global.d.ts
  packages/message-compiler/package.json
  packages/runtime/package.json
  packages/shared/src/index.ts
  packages/vue-i18n/package.json
  rollup.config.js
Labels: Type: Improvement

#250 improvement: display message function details
  packages/vue-i18n/src/devtools.ts
Labels: Type: Improvement

#251 improvement(message-compiler): Improves parse error messages
  packages/message-compiler/src/errors.ts
  packages/message-compiler/src/parser.ts
  packages/message-compiler/test/__snapshots__/parser.test.ts.snap
  packages/message-compiler/test/parser.test.ts
Labels: Type: Improvement

#255 fix cannot resolve computed property name
  packages/core-base/src/translate.ts
  packages/core-base/test/translate.test.ts
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/test/composer.test.ts
Labels: Type: Bug

#256 revert: change default ES module bundler module
  .textlintrc.js
  docs/.vitepress/config.js
  docs/advanced/optimization.md
  docs/installation.md
  packages/vue-i18n/package.json
Labels: Type: Improvement

#263 fix #262: test fail in some cases
  packages/vue-i18n/test/composer.test.ts
Labels: Type: Refactoring

#264 update docs
  docs/installation.md
Labels: Type: Documentation

#266 Fix casing of datetimeFormats option
  docs/essentials/datetime.md
Labels: Type: Documentation

#267 fix typo
  examples/lazy-loading/vite/index.html
Labels: Type: Example

#268 improvement: vue-devtools debugging
  .github/CONTRIBUTING.md
  packages/core-base/src/context.ts
  packages/core-base/src/datetime.ts
  packages/core-base/src/debugger/constants.ts
  packages/core-base/src/number.ts
  packages/core-base/src/translate.ts
  packages/vue-i18n/package.json
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/src/devtools.ts
  yarn.lock
Labels: Type: Improvement
