Repository intlify/vue-i18n, pull requests merged in 2020-11, with the labels that each got.

#176 fix: cannot pass modifiers options
  e2e/formatting/linked.test.js
  examples/composition/formatting/linked.html
  examples/legacy/formatting/linked.html
  src/legacy.ts
Labels: Type: Bug

#178 fix: can't assign to property "processor" on false: not an object
  src/composer.ts
Labels: Type: Bug

#180 fix: missing handler not returned
  examples/composition/formatting/linked.html
  examples/legacy/formatting/linked.html
  src/core/translate.ts
  test/composer.test.ts
  test/core/translate.test.ts
  test/legacy.test.ts
Labels: Type: Bug

#181 fix: improve warning message
  src/i18n.ts
  src/warnings.ts
Labels: Type: Improvement

#188 feat: export type prop from runtime
  src/composer.ts
  src/message/runtime.ts
  test/message/runtime.test.ts
Labels: Type: Feature

#190 fix: locale changing for legacy mode
  .textlintrc.js
  docs/advanced/composition.md
  docs/essentials/started.md
  src/composer.ts
  src/i18n.ts
  src/index.ts
  src/mixin.ts
  src/vue.d.ts
Labels: Type: Bug

#192 fix: cannot locale change for specified i18n custom blocks only
  jest.e2e.config.js
  jest.e2e.setup.js
  src/mixin.ts
Labels: Type: Bug

#197 improve: component injection properties typing hints on VSCode
  .github/workflows/test.yml
  .textlintrc.js
  docs/.vitepress/config.js
  docs/advanced/composition.md
  docs/advanced/directive.md
  docs/essentials/datetime.md
  docs/essentials/fallback.md
  docs/essentials/number.md
  docs/tooling.md
  package.json
  src/core/context.ts
  src/core/datetime.ts
  src/core/number.ts
  src/core/translate.ts
  src/legacy.ts
  src/message/runtime.ts
  src/vue.d.ts
Labels: Type: Improvement

#199 fix: plural rules compatibilites
  src/composer.ts
  src/legacy.ts
  test/composer.test.ts
  test/legacy.test.ts
Labels: Type: Bug

#200 feat: add te for composition API
  docs/advanced/composition.md
  src/composer.ts
  src/legacy.ts
  test/composer.test.ts
Labels: Type: Feature
