Repository intlify/vue-i18n, pull requests merged in 2020-09, with the labels that each got.

#104 improvement: tweaks interface for devtools
  src/i18n.ts
  src/mixin.ts
Labels: Type: Improvement

#110 fix: type exporting
  src/index.ts
Labels: Type: Bug

#111 improve i18n instance management
  src/core/context.ts
  src/i18n.ts
  src/plugin.ts
  test/i18n.test.ts
  test/plugin.test.ts
Labels: Type: Improvement

#115 fix: composition setup warning
  package.json
  src/components/DatetimeFormat.ts
  src/components/NumberFormat.ts
  src/components/Translation.ts
  src/composer.ts
  src/i18n.ts
  src/legacy.ts
  src/mixin.ts
  src/utils.ts
  test/__snapshots__/composer.test.ts.snap
  test/composer.test.ts
  yarn.lock
Labels: Type: Improvement

#116 optimize tree-shaking supporting
  .github/CONTRIBUTING.md
  README.md
  jest.config.js
  rollup.config.js
  src/errors.ts
  src/global.d.ts
  src/i18n.ts
  src/index.ts
  src/misc.ts
  src/plugin.ts
  test/plugin.test.ts
Labels: Type: Feature

#119 fix: merge custom block locale messages
  src/composer.ts
  test/composer.test.ts
Labels: Type: Improvement

#120 fix: typo
  src/core/context.ts
  src/core/datetime.ts
  src/core/number.ts
  src/core/translate.ts
Labels: Type: Refactoring

#122 feat: global props and methods injection for composable mode
  examples/composable/scope/global.html
  examples/composable/scope/inherit-locale.html
  examples/composable/scope/local.html
  examples/composable/started.html
  package.json
  src/directive.ts
  src/errors.ts
  src/i18n.ts
  src/index.ts
  src/vue.d.ts
  test/diretive.test.ts
  test/mixin.test.ts
Labels: Type: Feature

#125 fix: tree shaking optimaization
  package.json
  size-check/basic/index.html
  size-check/basic/package.json
  size-check/basic/src/App.vue
  size-check/basic/src/locales/en.json
  size-check/basic/src/locales/ja.json
  size-check/basic/src/main.js
  size-check/basic/vite.config.ts
  size-check/basic/yarn.lock
  size-check/both/index.html
  size-check/both/package.json
  size-check/both/src/App.vue
  size-check/both/src/locales/en.json
  size-check/both/src/locales/ja.json
  size-check/both/src/main.js
  size-check/both/vite.config.ts
  size-check/both/yarn.lock
  size-check/drop-legacy/index.html
  size-check/drop-legacy/package.json
  size-check/drop-legacy/src/App.vue
  size-check/drop-legacy/src/locales/en.json
  size-check/drop-legacy/src/locales/ja.json
  size-check/drop-legacy/src/main.js
  size-check/drop-legacy/vite.config.ts
  size-check/drop-legacy/yarn.lock
  size-check/min-install/index.html
  size-check/min-install/package.json
  size-check/min-install/src/App.vue
  size-check/min-install/src/locales/en.json
  size-check/min-install/src/locales/ja.json
  size-check/min-install/src/main.js
  size-check/min-install/vite.config.ts
  size-check/min-install/yarn.lock
  src/i18n.ts
Labels: Type: Performance
