Repository intlify/vue-i18n, pull requests merged in 2020-10, with the labels that each got.

#131 Update composer.ts
  src/composer.ts
Labels: Type: Refactoring

#134 Fix `UNEXPECTED_ERROR` message typo
  src/errors.ts
Labels: Type: Refactoring

#135 example: add lazy-loading
  examples/lazy-loading/vite/.gitignore
  examples/lazy-loading/vite/index.html
  examples/lazy-loading/vite/package.json
  examples/lazy-loading/vite/public/.gitkeep
  examples/lazy-loading/vite/src/App.vue
  examples/lazy-loading/vite/src/assets/.gitkeep
  examples/lazy-loading/vite/src/components/.gitkeep
  examples/lazy-loading/vite/src/i18n.ts
  examples/lazy-loading/vite/src/index.css
  examples/lazy-loading/vite/src/locales/en.js
  examples/lazy-loading/vite/src/locales/ja.js
  examples/lazy-loading/vite/src/main.ts
  examples/lazy-loading/vite/src/pages/About.vue
  examples/lazy-loading/vite/src/pages/Home.vue
  examples/lazy-loading/vite/src/router.ts
  examples/lazy-loading/vite/tsconfig.json
  examples/lazy-loading/vite/yarn.lock
  examples/lazy-loading/webpack/index.html
  examples/lazy-loading/webpack/package.json
  examples/lazy-loading/webpack/src/App.vue
  examples/lazy-loading/webpack/src/components/.gitkeep
  examples/lazy-loading/webpack/src/i18n.js
  examples/lazy-loading/webpack/src/index.css
  examples/lazy-loading/webpack/src/locales/en.json
  examples/lazy-loading/webpack/src/locales/ja.json
  examples/lazy-loading/webpack/src/main.js
  examples/lazy-loading/webpack/src/pages/About.vue
  examples/lazy-loading/webpack/src/pages/Home.vue
  examples/lazy-loading/webpack/src/router.js
  examples/lazy-loading/webpack/webpack.config.js
  examples/lazy-loading/webpack/yarn.lock
Labels: Type: Example

#139 feat: escape html parameter options
  README.md
  src/composer.ts
  src/core/context.ts
  src/core/translate.ts
  src/legacy.ts
  src/utils.ts
  test/core/context.test.ts
  test/core/translate.test.ts
Labels: Type: Feature

#140 add message format debugging tools for internal
  format-explorer/README.md
  format-explorer/package.json
  format-explorer/src/App.vue
  format-explorer/src/components/Editor.vue
  format-explorer/src/components/Navigation.vue
  format-explorer/src/index.css
  format-explorer/src/index.html
  format-explorer/src/index.ts
  format-explorer/src/shim-vue.d.ts
  format-explorer/src/theme.ts
  format-explorer/src/utils.ts
  format-explorer/tsconfig.json
  format-explorer/webpack.config.js
  format-explorer/yarn.lock
  package.json
Labels: Type: Maintenance

#147 feat: support source map for message functions
  README.md
  devtools-test/yarn.lock
  format-explorer/package.json
  format-explorer/src/App.vue
  format-explorer/src/components/Editor.vue
  format-explorer/src/components/Navigation.vue
  format-explorer/src/index.css
  format-explorer/src/utils.ts
  format-explorer/webpack.config.js
  format-explorer/yarn.lock
  package.json
  rollup.config.js
  src/message/compiler.ts
  src/message/generator.ts
  src/message/location.ts
  src/message/options.ts
  src/message/parser.ts
  test/message/__snapshots__/generator.test.ts.snap
  test/message/__snapshots__/parser.test.ts.snap
  test/message/__snapshots__/transformer.test.ts.snap
  test/message/generator.test.ts
  test/message/parser/__snapshots__/linked.test.ts.snap
  test/message/parser/__snapshots__/list.test.ts.snap
  test/message/parser/__snapshots__/literal.test.ts.snap
  test/message/parser/__snapshots__/modulo.test.ts.snap
  test/message/parser/__snapshots__/named.test.ts.snap
  test/message/parser/__snapshots__/plural.test.ts.snap
  test/message/parser/__snapshots__/text.test.ts.snap
  yarn.lock
Labels: Type: Feature

#150 tweak bundling
  rollup.config.js
  src/global.d.ts
  src/i18n.ts
  src/mixin.ts
  yarn.lock
Labels: Type: Performance

#153 port: escape ampersand
  src/utils.ts
Labels: Type: Breaking

#155 breaking: change to default legacy mode from compsable mode
  examples/composable/components/datetime-format.html
  examples/composable/components/number-format.html
  examples/composable/components/translation.html
  examples/composable/datetime.html
  examples/composable/directive/basic.html
  examples/composable/directive/object.html
  examples/composable/directive/plural.html
  examples/composable/directive/preserve.html
  examples/composable/fallback/basic.html
  examples/composable/fallback/component.html
  examples/composable/fallback/default-format.html
  examples/composable/fallback/format.html
  examples/composable/fallback/option.html
  examples/composable/fallback/suppress.html
  examples/composable/formatting/list.html
  examples/composable/formatting/literal.html
  examples/composable/formatting/named.html
  examples/composable/formatting/ruby.html
  examples/composable/missing/handler.html
  examples/composable/missing/option.html
  examples/composable/missing/suppress.html
  examples/composable/number.html
  examples/composable/plural/basic.html
  examples/composable/plural/custom.html
  examples/composable/scope/global.html
  examples/composable/scope/inherit-locale.html
  examples/composable/scope/local.html
  examples/composable/started.html
  examples/legacy/components/datetime-format.html
  examples/legacy/components/number-format.html
  examples/legacy/components/translation.html
  examples/legacy/datetime.html
  examples/legacy/directive/basic.html
  examples/legacy/directive/object.html
  examples/legacy/directive/plural.html
  examples/legacy/directive/preserve.html
  examples/legacy/fallback/basic.html
  examples/legacy/fallback/component.html
  examples/legacy/fallback/format.html
  examples/legacy/fallback/suppress.html
  examples/legacy/formatting/list.html
  examples/legacy/formatting/literal.html
  examples/legacy/formatting/named.html
  examples/legacy/formatting/ruby.html
  examples/legacy/missing/handler.html
  examples/legacy/missing/suppress.html
  examples/legacy/number.html
  examples/legacy/plural/basic.html
  examples/legacy/plural/custom.html
  examples/legacy/scope/global.html
  examples/legacy/scope/inherit-locale.html
  examples/legacy/scope/local.html
  examples/legacy/started.html
  src/i18n.ts
  test/components/Translation.test.ts
  test/i18n.test.ts
  test/ssr.test.ts
Labels: Type: Breaking

#157 breaking: change i18n global property
  docs/vue-i18n.createi18n.md
  docs/vue-i18n.i18n.global.md
  docs/vue-i18n.i18n.md
  docs/vue-i18n.vtdirective.md
  src/debugger/devtools.ts
  src/directive.ts
  src/i18n.ts
  src/plugin.ts
  test/helper.ts
  test/i18n.test.ts
Labels: Type: Breaking

#160 Update README.md
  README.md
Labels: Type: Documentation

#165 Allow d() to take an ISO string as parameter.
  src/composer.ts
  src/core/datetime.ts
  src/core/errors.ts
  test/composer.test.ts
  test/core/datetime.test.ts
Labels: Type: Feature

#167 fix: improvement errors
  src/errors.ts
  src/i18n.ts
  test/helper.ts
  test/i18n.test.ts
Labels: Type: Improvement

#168 fix: useScope inconsistency
  examples/composition/scope/inherit-locale.html
  examples/legacy/scope/inherit-locale.html
  src/i18n.ts
  test/i18n.test.ts
Labels: Type: Bug

#170 Fix readme link
  .github/ISSUE_TEMPLATE.md
  README.md
Labels: Type: Documentation
