Repository intlify/vue-i18n, pull requests merged in 2020-04, with the labels that each got.

#6 breaking: factory improvements
  examples/composable/component.html
  examples/composable/datetime.html
  examples/composable/fallback/basic.html
  examples/composable/fallback/default-format.html
  examples/composable/fallback/format.html
  examples/composable/fallback/option.html
  examples/composable/fallback/suppress.html
  examples/composable/formatting/list.html
  examples/composable/formatting/named.html
  examples/composable/formatting/ruby.html
  examples/composable/global.html
  examples/composable/missing/handler.html
  examples/composable/missing/option.html
  examples/composable/missing/suppress.html
  examples/composable/number.html
  examples/composable/plural/basic.html
  examples/composable/plural/custom.html
  examples/composable/started.html
  examples/legacy/component.html
  examples/legacy/datetime.html
  examples/legacy/fallback/basic.html
  examples/legacy/fallback/format.html
  examples/legacy/fallback/suppress.html
  examples/legacy/formatting/list.html
  examples/legacy/formatting/named.html
  examples/legacy/formatting/ruby.html
  examples/legacy/global.html
  examples/legacy/missing/handler.html
  examples/legacy/missing/suppress.html
  examples/legacy/number.html
  examples/legacy/plural/basic.html
  examples/legacy/plural/custom.html
  examples/legacy/started.html
  src/composer.ts
  src/i18n.ts
  src/index.ts
  src/legacy.ts
  src/mixin.ts
  src/plugin.ts
  src/use.ts
  src/utils.ts
  test/composer.test.ts
  test/legacy.test.ts
Labels: Type: Breaking

#7 Translation component `i18n-t` (In v8.x, it was called `i18n` component as Component interpolation feature)
  .github/workflows/test.yml
  README.md
  e2e/components/translation.test.js
  examples/composable/components/translation.html
  examples/legacy/components/translation.html
  src/components/index.ts
  src/components/interpolation.ts
  src/components/translation.ts
  src/composer.ts
  src/index.ts
  src/legacy.ts
  src/message/compiler.ts
  src/message/context.ts
  src/message/generator.ts
  src/plugin.ts
  src/runtime/context.ts
  src/runtime/translate.ts
  test/message/__snapshots__/compiler.test.ts.snap
  test/message/__snapshots__/context.test.ts.snap
  test/message/__snapshots__/generator.test.ts.snap
  test/message/compiler.test.ts
  test/message/context.test.ts
  test/message/generator.test.ts
  yarn.lock
Labels: Type: Breaking

#8 enhancement locale fallbacking
  examples/composable/fallback/basic.html
  examples/composable/fallback/default-format.html
  examples/composable/fallback/option.html
  examples/composable/fallback/suppress.html
  examples/composable/missing/handler.html
  examples/composable/missing/option.html
  examples/composable/missing/suppress.html
  src/composer.ts
  src/legacy.ts
  src/runtime/context.ts
  src/runtime/datetime.ts
  src/runtime/number.ts
  src/runtime/translate.ts
  test/composer.test.ts
  test/runtime/context.test.ts
  test/runtime/datetime.test.ts
  test/runtime/number.test.ts
  test/runtime/translate.test.ts
Labels: Type: Breaking

#9 number format component: `i18n-n`
  e2e/components/number-format.test.js
  examples/composable/components/number-format.html
  examples/legacy/components/number-format.html
  src/components/NumberFormat.ts
  src/composer.ts
  src/plugin.ts
  src/runtime/number.ts
  test/runtime/number.test.ts
Labels: Type: Feature

#10 support datetime format component
  .github/workflows/test.yml
  e2e/components/datetime-format.test.js
  examples/composable/components/datetime-format.html
  examples/composable/components/number-format.html
  examples/legacy/components/datetime-format.html
  examples/legacy/components/number-format.html
  jest-e2e-environment.js
  jest.config.js
  jest.e2e.config.js
  package.json
  src/components/DatetimeFormat.ts
  src/components/index.ts
  src/composer.ts
  src/plugin.ts
  yarn.lock
Labels: Type: Feature

#13 support vue3 beta
  package.json
  src/legacy.ts
  src/mixin.ts
  yarn.lock
Labels: Type: Improvement

#16 fix: cannot resolve object path
  src/runtime/translate.ts
  test/runtime/translate.test.ts
Labels: Type: Bug

#18 fix tokenizer
  .github/workflows/test.yml
  spec/syntax.ebnf
  src/index.ts
  src/message/tokenizer.ts
  test/message/__snapshots__/tokenizer.test.ts.snap
  test/message/tokenizer.test.ts
  yarn.lock
Labels: Type: Bug

#17 Minor typo fixes
  .github/CONTRIBUTING.md
  README.md
Labels: Type: Documentation

#20 feature placeholder literal
  README.md
  spec/syntax.ebnf
  src/index.ts
  src/message/compiler.ts
  src/message/errors.ts
  src/message/generator.ts
  src/message/options.ts
  src/message/parser.ts
  src/message/tokenizer.ts
  test/composer.test.ts
  test/message/__snapshots__/generator.test.ts.snap
  test/message/__snapshots__/parser.test.ts.snap
  test/message/__snapshots__/tokenizer.test.ts.snap
  test/message/generator.test.ts
  test/message/parser.test.ts
  test/message/tokenizer/literal.test.ts
  test/message/tokenizer/text.test.ts
Labels: Type: Feature

#21 add literal usage examples
  e2e/formatting/literal.test.js
  examples/composable/formatting/literal.html
  examples/legacy/formatting/literal.html
Labels: Type: Example

#22 deprecated linked key with using paren token
  spec/syntax.ebnf
  src/message/parser.ts
  src/message/tokenizer.ts
  test/message/__snapshots__/compiler.test.ts.snap
  test/message/__snapshots__/generator.test.ts.snap
  test/message/__snapshots__/parser.test.ts.snap
  test/message/__snapshots__/tokenizer.test.ts.snap
  test/message/__snapshots__/transformer.test.ts.snap
  test/message/compiler.test.ts
  test/message/context.test.ts
  test/message/generator.test.ts
  test/message/parser.test.ts
  test/message/tokenizer.test.ts
  test/message/tokenizer/linked.test.ts
  test/message/tokenizer/plural.test.ts
  test/message/transformer.test.ts
Labels: Type: Breaking

#23 fix: improve literal compilation error
  src/index.ts
  src/message/compiler.ts
  src/message/errors.ts
  src/message/generator.ts
  src/message/options.ts
  src/message/parser.ts
  src/message/tokenizer.ts
  src/message/transformer.ts
  test/message/__snapshots__/compiler.test.ts.snap
  test/message/__snapshots__/tokenizer.test.ts.snap
  test/message/compiler.test.ts
  test/message/errors.test.ts
  test/message/tokenizer.test.ts
  test/message/tokenizer/literal.test.ts
Labels: Type: Improvement

#24 fix: compilation error handling
  src/composer.ts
  src/runtime/context.ts
  src/runtime/translate.ts
  src/utils.ts
  test/__snapshots__/utils.test.ts.snap
  test/runtime/translate.test.ts
  test/utils.test.ts
Labels: Type: Improvement

#25 fix: plural syntax error with parser
  src/message/errors.ts
  src/message/parser.ts
  src/message/tokenizer.ts
  test/message/parser/__snapshots__/list.test.ts.snap
  test/message/parser/__snapshots__/named.test.ts.snap
  test/message/parser/__snapshots__/plural.test.ts.snap
  test/message/parser/list.test.ts
  test/message/parser/named.test.ts
  test/message/parser/plural.test.ts
  test/message/tokenizer/literal.test.ts
Labels: Type: Improvement

#26 compile error improvements
  .gitignore
  README.md
  src/message/compiler.ts
  src/message/errors.ts
  src/message/generator.ts
  src/message/options.ts
  src/message/parser.ts
  src/message/tokenizer.ts
  src/message/transformer.ts
  src/runtime/translate.ts
  test/composer.test.ts
  test/message/__snapshots__/generator.test.ts.snap
  test/message/__snapshots__/tokenizer.test.ts.snap
  test/message/parser/__snapshots__/literal.test.ts.snap
  test/message/parser/__snapshots__/text.test.ts.snap
  test/message/parser/linked.test.ts
  test/message/parser/list.test.ts
  test/message/parser/literal.test.ts
  test/message/parser/named.test.ts
  test/message/parser/plural.test.ts
  test/message/parser/text.test.ts
  test/message/tokenizer.test.ts
  test/message/tokenizer/linked.test.ts
  test/message/tokenizer/list.test.ts
  test/message/tokenizer/literal.test.ts
  test/message/tokenizer/named.test.ts
Labels: Type: Improvement

#27 fix: add invalid token errors in placeholder
  src/message/tokenizer.ts
  test/message/__snapshots__/tokenizer.test.ts.snap
  test/message/tokenizer/named.test.ts
Labels: Type: Improvement

#28 fix: plural compiler bug
  src/message/context.ts
  test/message/__snapshots__/compiler.test.ts.snap
  test/message/__snapshots__/context.test.ts.snap
  test/message/compiler.test.ts
  test/message/context.test.ts
Labels: Type: Bug

#29 breaking: HTML message warning
  README.md
  src/composer.ts
  src/legacy.ts
  src/message/compiler.ts
  src/message/options.ts
  src/runtime/context.ts
  src/runtime/translate.ts
  test/legacy.test.ts
  test/message/__snapshots__/compiler.test.ts.snap
  test/message/compiler.test.ts
  test/runtime/translate.test.ts
Labels: Type: Breaking

#31 feat: generator mode
  src/message/context.ts
  src/message/generator.ts
  src/message/options.ts
  src/message/parser.ts
  src/message/transformer.ts
  test/message/__snapshots__/compiler.test.ts.snap
  test/message/__snapshots__/generator.test.ts.snap
  test/message/__snapshots__/transformer.test.ts.snap
  test/message/generator.test.ts
  test/message/transformer.test.ts
Labels: Type: Feature
