Repository intlify/vue-i18n, pull requests merged in 2020-08, with the labels that each got.

#80 fix modulo case
  src/message/tokenizer.ts
  test/message/__snapshots__/compiler.test.ts.snap
  test/message/__snapshots__/tokenizer.test.ts.snap
  test/message/compiler.test.ts
  test/message/parser/__snapshots__/modulo.test.ts.snap
  test/message/parser/modulo.test.ts
  test/message/tokenizer/linked.test.ts
  test/message/tokenizer/named.test.ts
  test/message/tokenizer/plural.test.ts
  test/message/tokenizer/text.test.ts
Labels: Type: Bug

#81 remove computed wrapping
  src/composer.ts
Labels: Type: Improvement

#82 port i18n or i18n-d component tag props
  src/components/Translation.ts
  src/components/base.ts
  src/components/formatRenderer.ts
  test/components/DatetimeFormat.test.ts
  test/components/NumberFormat.test.ts
  test/components/Translation.test.ts
Labels: Type: Feature

#84 support server-side rendering
  package.json
  src/directive.ts
  test/diretive.test.ts
  test/ssr.test.ts
  yarn.lock
Labels: Type: Feature

#87 feat: how to get locale messages from a given key
  README.md
  src/composer.ts
  src/legacy.ts
  src/mixin.ts
  test/composer.test.ts
  test/legacy.test.ts
Labels: Type: Feature

#94 refactor: simplify scope cases
  src/i18n.ts
Labels: Type: Refactoring

#96 feat: support vue3 rc8
  .eslintrc.js
  examples/composable/components/datetime-format.html
  examples/composable/components/number-format.html
  examples/legacy/components/datetime-format.html
  examples/legacy/components/number-format.html
  package.json
  src/components/DatetimeFormat.ts
  src/components/NumberFormat.ts
  src/components/Translation.ts
  src/components/base.ts
  src/components/formatRenderer.ts
  src/core/context.ts
  src/i18n.ts
  test/__snapshots__/i18n.test.ts.snap
  test/components/Translation.test.ts
  test/helper.ts
  test/i18n.test.ts
  test/ssr.test.ts
  yarn.lock
Labels: Type: Feature

#97 feat: support for devtools interface
  jest.config.js
  rollup.config.js
  src/devtools.ts
  src/global.d.ts
  src/i18n.ts
  src/index.ts
  src/misc.ts
  src/mixin.ts
  src/utils.ts
Labels: Type: Feature

#99 fix: type definition build errors
  ship.config.js
  src/components/DatetimeFormat.ts
  src/components/NumberFormat.ts
  src/components/Translation.ts
  src/components/base.ts
  src/plugin.ts
  yarn.lock
Labels: Type: Bug

#101 Fix devtools typo
  rollup.config.js
Labels: Type: Bug
