Repository intlify/vue-i18n, pull requests merged in 2021-01, with the labels that each got.

#273 improvement: vue-i18n debugging on vue-devtools
  packages/vue-i18n/src/devtools.ts
  packages/vue-i18n/src/i18n.ts
  packages/vue-i18n/src/misc.ts
Labels: Type: Improvement

#282 improvement: bundle-size
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/src/legacy.ts
Labels: Type: Performance

#287 fix: export types
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/runtime.ts
Labels: Type: Bug

#290 fix: fallback root warnings
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/test/composer.test.ts
Labels: Type: Bug

#294 Add support for flat json separated with dot('.')
  packages/message-resolver/src/index.ts
  packages/message-resolver/test/index.test.ts
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/test/i18n.test.ts
Labels: Type: Improvement

#299 modify .gitignore: ignore .vscode directory
  .gitignore
Labels: Type: Maintenance

#300 fix some typos
  packages/core-base/src/compile.ts
  packages/core-base/src/datetime.ts
  packages/core-base/src/number.ts
  packages/core-base/src/translate.ts
  packages/core-base/test/datetime.test.ts
  packages/core-base/test/emitter.test.ts
  packages/core-base/test/translate.test.ts
  packages/message-compiler/src/errors.ts
  packages/message-compiler/src/parser.ts
  packages/message-compiler/src/tokenizer.ts
  packages/message-compiler/src/transformer.ts
  packages/message-compiler/test/tokenizer/literal.test.ts
  packages/message-compiler/test/tokenizer/named.test.ts
  packages/shared/src/index.ts
  packages/vue-i18n/src/components/DatetimeFormat.ts
  packages/vue-i18n/src/components/NumberFormat.ts
  packages/vue-i18n/src/components/Translation.ts
  packages/vue-i18n/src/components/base.ts
  packages/vue-i18n/src/components/formatRenderer.ts
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/src/errors.ts
  packages/vue-i18n/src/i18n.ts
  packages/vue-i18n/src/legacy.ts
  packages/vue-i18n/src/mixin.ts
  packages/vue-i18n/src/vue.d.ts
  packages/vue-i18n/src/warnings.ts
  packages/vue-i18n/test/__snapshots__/i18n.test.ts.snap
  packages/vue-i18n/test/composer.test.ts
  packages/vue-i18n/test/i18n.test.ts
Labels: Type: Refactoring

#301 chore/update-guide-doc-error
  docs/guide/index.md
Labels: Type: Documentation

#303 fix: locale type importing
  packages/vue-i18n/src/components/base.ts
Labels: Type: Bug

#308 Revert "Add support for flat json separated with dot('.')"
  packages/message-resolver/src/index.ts
  packages/message-resolver/test/index.test.ts
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/test/i18n.test.ts
Labels: Type: Bug

#312 Fix spelling line 195 for sfc doc : lessages to messages
  docs/guide/advanced/sfc.md
Labels: Type: Documentation

#313 fix some typos in docs/
  docs/.vitepress/config.js
  docs/api/injection.md
  docs/guide/advanced/component.md
  docs/guide/advanced/composition.md
  docs/guide/advanced/function.md
  docs/guide/advanced/lazy.md
  docs/guide/advanced/sfc.md
  docs/guide/essentials/datetime.md
  docs/guide/essentials/local.md
  docs/guide/essentials/number.md
  docs/guide/essentials/scope.md
  docs/guide/essentials/syntax.md
  docs/guide/migration/breaking.md
  docs/guide/migration/composition.md
  docs/guide/migration/features.md
Labels: Type: Documentation

#316 update composition api docs
  docs/guide/advanced/composition.md
Labels: Type: Documentation

#317 update lazy loading docs
  docs/guide/advanced/lazy.md
Labels: Type: Documentation

#318 simplify some tests
  packages/vue-i18n/test/i18n.test.ts
Labels: Type: Refactoring

#323 Fix typos in readme.md
  README.md
Labels: Type: Documentation

#329 fix typo in docs lazy.md
  docs/guide/advanced/lazy.md
Labels: Type: Documentation
