Repository intlify/vue-i18n, pull requests merged in 2021-10, with the labels that each got.

#713 fix: Maximum call stack size
  packages/message-compiler/src/tokenizer.ts
  packages/message-compiler/test/fixtures/20_newsgroups_alt_atheism_51060.txt
  packages/message-compiler/test/tokenizer.test.ts
  packages/vue-i18n-core/src/i18n.ts
Labels: Type: Bug

#715 fix: vue-i18n components scope resolving in Legacy API mode
  packages/vue-i18n-core/src/components/DatetimeFormat.ts
  packages/vue-i18n-core/src/components/NumberFormat.ts
  packages/vue-i18n-core/src/components/Translation.ts
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/legacy.ts
  packages/vue-i18n-core/src/mixins/next.ts
  packages/vue-i18n-core/src/symbols.ts
  packages/vue-i18n-core/test/components/Translation.test.ts
Labels: Type: Bug

#718 example: add SSR example for Vite
  examples/ssr/vite/README.md
  examples/ssr/vite/dep-import-type/deep/index.d.ts
  examples/ssr/vite/dep-import-type/package.json
  examples/ssr/vite/example-external-component/ExampleExternalComponent.vue
  examples/ssr/vite/example-external-component/index.js
  examples/ssr/vite/example-external-component/package.json
  examples/ssr/vite/index.html
  examples/ssr/vite/package.json
  examples/ssr/vite/prerender.js
  examples/ssr/vite/server.js
  examples/ssr/vite/src/App.vue
  examples/ssr/vite/src/assets/fonts/Inter-Italic.woff
  examples/ssr/vite/src/assets/fonts/Inter-Italic.woff2
  examples/ssr/vite/src/assets/logo.png
  examples/ssr/vite/src/components/Foo.jsx
  examples/ssr/vite/src/components/ImportType.vue
  examples/ssr/vite/src/components/foo.css
  examples/ssr/vite/src/entry-client.js
  examples/ssr/vite/src/entry-server.js
  examples/ssr/vite/src/i18n.js
  examples/ssr/vite/src/locales/en.json
  examples/ssr/vite/src/locales/ja.json
  examples/ssr/vite/src/main.js
  examples/ssr/vite/src/pages/About.vue
  examples/ssr/vite/src/pages/External.vue
  examples/ssr/vite/src/pages/Home.vue
  examples/ssr/vite/src/router.js
  examples/ssr/vite/vite.config.js
  examples/ssr/vite/vite.config.noexternal.js
  examples/ssr/vite/yarn.lock
Labels: Type: Example

#720 fix: bring bug fixes from v9.2.0-beta.11
  packages/message-compiler/src/tokenizer.ts
  packages/message-compiler/test/fixtures/20_newsgroups_alt_atheism_51060.txt
  packages/message-compiler/test/tokenizer.test.ts
  packages/vue-i18n/src/components/DatetimeFormat.ts
  packages/vue-i18n/src/components/NumberFormat.ts
  packages/vue-i18n/src/components/Translation.ts
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/src/i18n.ts
  packages/vue-i18n/src/legacy.ts
  packages/vue-i18n/src/mixin.ts
  packages/vue-i18n/test/i18n.test.ts
Labels: Type: Bug

#723 fix: Built-in components bugs
  packages/vue-i18n/src/i18n.ts
  packages/vue-i18n/test/i18n.test.ts
Labels: Type: Bug

#725 fix: builtin components bugs
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/test/i18n.test.ts
Labels: Type: Bug

#742 fix: node esm for nuxt3
  packages/core-base/package.json
  packages/core/package.json
  packages/devtools-if/package.json
  packages/message-compiler/package.json
  packages/petite-vue-i18n/package.json
  packages/shared/package.json
  packages/vue-devtools/package.json
  packages/vue-i18n-bridge/package.json
  packages/vue-i18n-core/package.json
  packages/vue-i18n/package.json
Labels: Type: Improvement

#754 fix: remove terser option pure_getters: true, avoid wrong tree-shaking
  rollup.config.js
Labels: Type: Bug
