Repository intlify/vue-i18n, pull requests merged in 2021-12, with the labels that each got.

#820 fix: cannot work correctly v-for on Translation component
  packages/vue-i18n-core/src/components/utils.ts
  packages/vue-i18n-core/test/components/Translation.test.ts
Labels: Type: Bug

#839 doc: update package url
  docs/installation.md
  docs/ja/installation.md
Labels: Type: Documentation

#838 feat: composer type definition extending (**experimental feature**)
  packages/vue-i18n-core/src/composer.ts
  test-d/vue-i18n/composer.test-d.ts
Labels: Type: Feature

#843 fix: export composer custom type definition
  packages/petite-vue-i18n/src/index.ts
  packages/petite-vue-i18n/src/runtime.ts
  packages/vue-i18n-bridge/src/index.ts
  packages/vue-i18n-bridge/src/runtime.ts
  packages/vue-i18n-core/src/index.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/runtime.ts
Labels: Type: Bug

#848 fix typo petitle-vue-i18n
  packages/petite-vue-i18n/README.md
Labels: Type: Documentation

#855 fix: not correct error and warning codes
  packages/core-base/src/errors.ts
  packages/vue-i18n-core/src/errors.ts
  packages/vue-i18n-core/src/warnings.ts
Labels: Type: Bug

#856 fix: inherit warn html message setting option
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/test/issues.test.ts
Labels: Type: Bug
