Repository intlify/vue-i18n, pull requests merged in 2021-03, with the labels that each got.

#369 Fix eslint warning in example project
  examples/lazy-loading/vite/src/App.vue
  examples/lazy-loading/webpack/src/App.vue
Labels: Type: Example

#370 Fix typo in docstring
  packages/vue-i18n/src/i18n.ts
Labels: Type: Documentation

#372 fix: cannot use underscore as indentifier
  packages/message-compiler/src/tokenizer.ts
  packages/message-compiler/test/__snapshots__/compiler.test.ts.snap
  packages/message-compiler/test/__snapshots__/parser.test.ts.snap
  packages/message-compiler/test/compiler.test.ts
  packages/message-compiler/test/parser.test.ts
  packages/message-compiler/test/tokenizer/linked.test.ts
  packages/message-compiler/test/tokenizer/named.test.ts
  spec/syntax.ebnf
Labels: Type: Bug

#374 fix: cannot warn fallback root
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/src/legacy.ts
  packages/vue-i18n/test/composer.test.ts
Labels: Type: Bug

#384 support suppress esm-bundler feature flags warning
  jest.config.js
  packages/global.d.ts
  packages/vue-i18n/README.md
  packages/vue-i18n/src/misc.ts
  rollup.config.js
Labels: Type: Improvement

#386 feat: Vue I18n Data Editing at DevTools
  packages/vue-i18n/src/devtools.ts
Labels: Type: Feature

#387 improvement: Vue I18n Devtools plugin info
  packages/vue-i18n/src/devtools.ts
Labels: Type: Improvement

#397 fix: Support for browsers that don't support object spread literals
  packages/message-compiler/src/compiler.ts
  packages/message-compiler/src/parser.ts
  packages/shared/src/index.ts
  packages/vue-i18n/src/components/DatetimeFormat.ts
  packages/vue-i18n/src/components/NumberFormat.ts
  packages/vue-i18n/src/components/Translation.ts
  packages/vue-i18n/src/components/formatRenderer.ts
Labels: Type: Improvement

#402 Add support for flat json separated with dot('.')
  packages/message-resolver/src/index.ts
  packages/message-resolver/test/index.test.ts
  packages/shared/src/index.ts
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/src/legacy.ts
  packages/vue-i18n/test/i18n.test.ts
Labels: Type: Feature

#403 fix: cannot fallback at tm / $tm
  docs/api/injection.md
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/src/legacy.ts
  packages/vue-i18n/src/vue.d.ts
  packages/vue-i18n/test/composer.test.ts
  packages/vue-i18n/test/legacy.test.ts
Labels: Type: Bug

#404 fix: suppress console for devtools flag
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/runtime.ts
Labels: Type: Bug

#406 Add easy-i18n as third-party tool
  docs/ecosystem/third.md
Labels: Type: Documentation

#410 fix warning: Missing associated label
  examples/composition/components/translation.html
  examples/composition/datetime.html
  examples/composition/directive/basic.html
  examples/composition/formatting/linked.html
  examples/composition/formatting/list.html
  examples/composition/formatting/literal.html
  examples/composition/formatting/named.html
  examples/composition/formatting/ruby.html
  examples/composition/functions/linked.html
  examples/composition/functions/list.html
  examples/composition/functions/named.html
  examples/composition/number.html
  examples/composition/scope/global.html
  examples/composition/scope/inherit-locale.html
  examples/composition/scope/local.html
  examples/composition/started.html
  examples/lazy-loading/vite/src/App.vue
  examples/lazy-loading/webpack/src/App.vue
  examples/legacy/components/translation.html
  examples/legacy/datetime.html
  examples/legacy/directive/basic.html
  examples/legacy/formatting/linked.html
  examples/legacy/formatting/list.html
  examples/legacy/formatting/literal.html
  examples/legacy/formatting/named.html
  examples/legacy/formatting/ruby.html
  examples/legacy/functions/linked.html
  examples/legacy/functions/list.html
  examples/legacy/functions/named.html
  examples/legacy/number.html
  examples/legacy/scope/global.html
  examples/legacy/scope/inherit-locale.html
  examples/legacy/scope/local.html
  examples/legacy/started.html
Labels: Type: Example

#411 feat: resolve locale message translation new API `rt`
  docs/api/injection.md
  docs/guide/advanced/composition.md
  packages/core-base/src/translate.ts
  packages/core-base/test/translate.test.ts
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/src/i18n.ts
  packages/vue-i18n/src/legacy.ts
  packages/vue-i18n/src/mixin.ts
  packages/vue-i18n/src/vue.d.ts
  packages/vue-i18n/test/composer.test.ts
  packages/vue-i18n/test/legacy.test.ts
  packages/vue-i18n/test/mixin.test.ts
  renovate.json
Labels: Type: Feature

#417 Coherent update from 'best-fit' to 'best fit'
  packages/core-base/src/types.ts
Labels: Type: Improvement
