Repository intlify/vue-i18n, pull requests merged in 2021-07, with the labels that each got.

#545 Allow number and boolean in args of number formatting
  docs/api/injection.md
  docs/ja/api/injection.md
  packages/vue-i18n/src/legacy.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Improvement

#555 docs: add `defaultSFCLocale` and `globalSFCScope` to sfc
  docs/guide/advanced/sfc.md
Labels: Type: Documentation

#560 breaking: drop node v10
  packages/core-base/package.json
  packages/core/package.json
  packages/devtools-if/package.json
  packages/message-compiler/package.json
  packages/message-resolver/package.json
  packages/runtime/package.json
  packages/shared/package.json
  packages/vue-devtools/package.json
  packages/vue-i18n/package.json
Labels: Type: Breaking

#570 fix: __INTLIFY_PROD_DEVTOOLS__ is not defined (#532)
  packages/core-base/src/index.ts
Labels: Type: Bug

#578 support for Vue 3.1
  package.json
  packages/vue-i18n/src/components/DatetimeFormat.ts
  packages/vue-i18n/src/components/NumberFormat.ts
  packages/vue-i18n/src/components/Translation.ts
  packages/vue-i18n/src/plugin.ts
  packages/vue-i18n/test/__snapshots__/composer.test.ts.snap
  packages/vue-i18n/test/ssr.test.ts
  yarn.lock
Labels: Type: Improvement

#582 docs: add typescript section to advanced
  docs/.vitepress/config.js
  docs/guide/advanced/typescript.md
  docs/ja/guide/advanced/typescript.md
  docs/public/ts-support-1.png
  docs/public/ts-support-2.png
  docs/public/ts-support-3.gif
  examples/type-safe/global-type-definition/src/components/HelloWorld.vue
  examples/type-safe/type-annotation/src/components/GlobalScope.vue
  examples/type-safe/type-annotation/src/components/LocalScope.vue
  examples/type-safe/type-annotation/src/locales/en-US.json
Labels: Type: Documentation

#583 improvement: deprecated __VUE_I18N_PROD_DEVTOOLS__ feature flag
  docs/guide/advanced/optimization.md
  packages/size-check-vue-i18n/rollup.config.js
  packages/vue-i18n/README.md
  packages/vue-i18n/src/misc.ts
  rollup.config.js
Labels: Type: Improvement

#584 improvement: reduce size
  packages/core-base/src/errors.ts
  packages/vue-i18n/src/errors.ts
  packages/vue-i18n/src/warnings.ts
Labels: Type: Improvement

#592 improvement: petite-vue-i18n tree shaking
  packages/petite-vue-i18n/package.json
  packages/size-check-petite-vue-i18n/src/main.ts
  packages/size-check-petite-vue-i18n/vite.config.ts
  packages/size-check-vue-i18n/src/App.vue
  packages/size-check-vue-i18n/src/main.ts
Labels: Type: Improvement

#593 improvement: vue-i18n tree shaking
  packages/vue-i18n/package.json
Labels: Type: Improvement

#595 fix: build feature flags
  examples/petite/formatting/linked.html
  package.json
  packages/petite-vue-i18n/src/index.ts
  packages/petite-vue-i18n/src/runtime.ts
  packages/petite-vue-i18n/src/vue.d.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/runtime.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Bug

#602 fix null access of __VUE_I18n__
  packages/vue-i18n-core/src/devtools.ts
Labels: Type: Bug
