Repository intlify/vue-i18n, pull requests merged in 2021-04, with the labels that each got.

#418 Modify some router setups in example projects
  examples/lazy-loading/vite/src/router.ts
  examples/lazy-loading/webpack/src/router.js
Labels: Type: Example

#419 fix some typos in examples/
  examples/composition/directive/basic.html
  examples/composition/functions/named.html
  examples/composition/scope/inherit-locale.html
  examples/composition/started.html
  examples/lazy-loading/vite/src/App.vue
  examples/lazy-loading/webpack/src/App.vue
  examples/lazy-loading/webpack/src/i18n.js
  examples/legacy/directive/basic.html
  examples/legacy/functions/named.html
Labels: Type: Example

#420 Fix typos in Composition API page
  docs/guide/advanced/composition.md
Labels: Type: Documentation

#422 fix: Intl type definition for TS 4.2
  package.json
  packages/core-base/src/types.ts
  packages/core-base/test/datetime.test.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/runtime.ts
  packages/vue-i18n/test/__snapshots__/composer.test.ts.snap
  packages/vue-i18n/test/components/DatetimeFormat.test.ts
  packages/vue-i18n/test/helper.ts
  packages/vue-i18n/test/mixin.test.ts
  yarn.lock
Labels: Type: Improvement

#423 chore: script change to typescript
  jest-puppeteer.config.js
  package.json
  packages/size-check-core/package.json
  packages/size-check-vue-i18n/package.json
  scripts/build.js
  scripts/build.ts
  scripts/dev.js
  scripts/dev.ts
  scripts/fixpack.js
  scripts/fixpack.ts
  scripts/serve.js
  scripts/serve.ts
  scripts/utils.js
  scripts/utils.ts
  yarn.lock
Labels: Type: Maintenance

#425 refactor: move emitter to @intlify/shared
  packages/core-base/src/debugger/constants.ts
  packages/core-base/src/debugger/index.ts
  packages/shared/src/emittable.ts
  packages/shared/src/emitter.ts
  packages/shared/src/index.ts
  packages/shared/src/utils.ts
  packages/shared/test/__snapshots__/utils.test.ts.snap
  packages/shared/test/emitter.test.ts
  packages/shared/test/utils.test.ts
Labels: Type: Refactoring

#433 experimental: Hooking for `@intlify/devtools`
  .vscode/settings.json
  packages/core-base/package.json
  packages/core-base/src/context.ts
  packages/core-base/src/devtools.ts
  packages/core-base/src/index.ts
  packages/core-base/src/translate.ts
  packages/core-base/src/types.ts
  packages/core-base/test/devtools.test.ts
  packages/devtools-if/LICENSE
  packages/devtools-if/README.md
  packages/devtools-if/api-extractor.json
  packages/devtools-if/index.js
  packages/devtools-if/package.json
  packages/devtools-if/src/index.ts
  packages/devtools-if/test/.gitkeep
  packages/vue-i18n/package.json
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/src/i18n.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/legacy.ts
  packages/vue-i18n/src/mixin.ts
  packages/vue-i18n/src/runtime.ts
  packages/vue-i18n/src/vue.d.ts
  packages/vue-i18n/test/composer.test.ts
  packages/vue-i18n/test/i18n.test.ts
Labels: Type: Feature

#434 breaking: split devtools production feature flags
  docs/guide/advanced/optimization.md
  packages/core-base/src/context.ts
  packages/core-base/src/translate.ts
  packages/global.d.ts
  packages/size-check-vue-i18n/rollup.config.js
  packages/vue-i18n/README.md
  packages/vue-i18n/src/devtools.ts
  packages/vue-i18n/src/i18n.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/misc.ts
  packages/vue-i18n/src/mixin.ts
  packages/vue-i18n/src/runtime.ts
  rollup.config.js
Labels: Type: Breaking

#436 fix: cannot defined feature flags accessing
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/misc.ts
  packages/vue-i18n/src/runtime.ts
Labels: Type: Bug

#441 fix: typing errors
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Bug

#446 experimental: improve meta for intlify devtools
  packages/core-base/src/context.ts
  packages/core-base/src/translate.ts
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/src/i18n.ts
  packages/vue-i18n/src/legacy.ts
  packages/vue-i18n/src/mixin.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Improvement

#450 experimental: fix devtools-if
  packages/core-base/src/devtools.ts
  packages/core-base/test/devtools.test.ts
  packages/devtools-if/src/index.ts
  packages/vue-i18n/test/i18n.test.ts
Labels: Type: Improvement

#449 Japanese translation (~essential)
  docs/.vitepress/config.js
  docs/ja/api/injection.md
  docs/ja/ecosystem/official.md
  docs/ja/ecosystem/third.md
  docs/ja/guide/advanced/component.md
  docs/ja/guide/advanced/composition.md
  docs/ja/guide/advanced/directive.md
  docs/ja/guide/advanced/function.md
  docs/ja/guide/advanced/lazy.md
  docs/ja/guide/advanced/optimization.md
  docs/ja/guide/advanced/sfc.md
  docs/ja/guide/essentials/datetime.md
  docs/ja/guide/essentials/fallback.md
  docs/ja/guide/essentials/local.md
  docs/ja/guide/essentials/number.md
  docs/ja/guide/essentials/pluralization.md
  docs/ja/guide/essentials/scope.md
  docs/ja/guide/essentials/syntax.md
  docs/ja/guide/index.md
  docs/ja/guide/migration/breaking.md
  docs/ja/guide/migration/composition.md
  docs/ja/guide/migration/features.md
  docs/ja/index.md
  docs/ja/installation.md
  docs/ja/introduction.md
  docs/ja/v8-docs.md
Labels: Type: Documentation

#454 fix: remove object spread literals with object assing
  docs/.vitepress/theme/index.ts
  packages/core-base/src/context.ts
  packages/core-base/src/datetime.ts
  packages/core-base/src/number.ts
  packages/core-base/src/translate.ts
  packages/vue-i18n/src/components/formatRenderer.ts
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/src/i18n.ts
  packages/vue-i18n/src/legacy.ts
  packages/vue-i18n/test/helper.ts
Labels: Type: Refactoring

#453 Support passing composer instance to Translation component
  packages/vue-i18n/src/components/DatetimeFormat.ts
  packages/vue-i18n/src/components/NumberFormat.ts
  packages/vue-i18n/src/components/Translation.ts
  packages/vue-i18n/src/components/base.ts
Labels: Type: Improvement

#459 fix vue-i18n type definition broken
  packages/vue-i18n/src/components/base.ts
Labels: Type: Bug

#477 feat: custom message resolver
  packages/core-base/src/context.ts
  packages/core-base/src/translate.ts
  packages/message-resolver/src/index.ts
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/src/legacy.ts
  packages/vue-i18n/test/components/Translation.test.ts
  packages/vue-i18n/test/composer.test.ts
  packages/vue-i18n/test/legacy.test.ts
Labels: Type: Feature

#478 improvement: target component highlighting on i18n resources inspector
  package.json
  packages/vue-i18n/package.json
  packages/vue-i18n/src/devtools.ts
  yarn.lock
Labels: Type: Improvement

#484 Fix syntax error in quote example.
  docs/guide/essentials/syntax.md
Labels: Type: Documentation

#485 simplify function isResolvedTranslateMessage in composer.ts
  packages/vue-i18n/src/composer.ts
Labels: Type: Refactoring
