Repository intlify/vue-i18n, pull requests merged in 2021-05, with the labels that each got.

#487 Add some tests about numberFormats
  docs/guide/essentials/number.md
  packages/vue-i18n/test/composer.test.ts
Labels: Type: Documentation

#489 Type safe improvements
  .gitignore
  .vscode/settings.json
  examples/lazy-loading/vite/package.json
  examples/lazy-loading/vite/src/App.vue
  examples/lazy-loading/vite/src/i18n.ts
  examples/lazy-loading/vite/yarn.lock
  examples/type-safe/.gitignore
  examples/type-safe/README.md
  examples/type-safe/index.html
  examples/type-safe/package.json
  examples/type-safe/public/favicon.ico
  examples/type-safe/src/App.vue
  examples/type-safe/src/assets/logo.png
  examples/type-safe/src/components/GlobalScope.vue
  examples/type-safe/src/components/LocalScope.vue
  examples/type-safe/src/components/en-US.json
  examples/type-safe/src/locales/en-US.json
  examples/type-safe/src/locales/schema.ts
  examples/type-safe/src/main.ts
  examples/type-safe/src/shims-vue.d.ts
  examples/type-safe/tsconfig.json
  examples/type-safe/vite.config.ts
  examples/type-safe/yarn.lock
  package.json
  packages/core-base/src/context.ts
  packages/core-base/src/datetime.ts
  packages/core-base/src/number.ts
  packages/core-base/src/translate.ts
  packages/core-base/src/types/index.ts
  packages/core-base/src/types/intl.ts
  packages/core-base/src/types/utils.ts
  packages/core-base/test/context.test.ts
  packages/core-base/test/datetime.test.ts
  packages/core-base/test/number.test.ts
  packages/core-base/test/translate.test.ts
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/src/devtools.ts
  packages/vue-i18n/src/directive.ts
  packages/vue-i18n/src/i18n.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/legacy.ts
  packages/vue-i18n/src/mixin.ts
  packages/vue-i18n/src/plugin.ts
  packages/vue-i18n/src/runtime.ts
  packages/vue-i18n/src/vue.d.ts
  packages/vue-i18n/test/composer.test.ts
  packages/vue-i18n/test/helper.ts
  packages/vue-i18n/test/i18n.test.ts
  packages/vue-i18n/test/legacy.test.ts
  packages/vue-i18n/test/mixin.test.ts
  scripts/api/processor.js
  test-d/core-base/context.test-d.ts
  test-d/core-base/datetime.test-d.ts
  test-d/core-base/number.test-d.ts
  test-d/core-base/translate.test-d.ts
  test-d/schema.ts
  test-d/vue-i18n/composer.test-d.ts
  test-d/vue-i18n/i18n.test-d.ts
  test-d/vue-i18n/legacy.test-d.ts
Labels: Type: Breaking, Type: Improvement

#510 fix: lazy-loading example
  examples/lazy-loading/vite/src/i18n.ts
Labels: Type: Example

#514 Fix __FEATURE_ESM_BUNDLER_WARN__ flag can not be configured
  jest.config.js
  packages/global.d.ts
  packages/vue-i18n/README.md
  packages/vue-i18n/src/misc.ts
  rollup.config.js
Labels: Type: Breaking

#515 fix #383
  packages/core-base/src/datetime.ts
  packages/core-base/test/datetime.test.ts
Labels: Type: Bug
