Repository intlify/vue-i18n, pull requests merged in 2021-08, with the labels that each got.

#606 Fix type-safe example warning
  examples/type-safe/global-type-definition/src/components/HelloWorld.vue
  examples/type-safe/global-type-definition/vite.config.ts
  examples/type-safe/type-annotation/vite.config.ts
Labels: Type: Example

#616 docs: typo in typescript.md
  docs/guide/advanced/typescript.md
Labels: Type: Documentation

#619 improvement: bundle source map at message-compiler
  .github/workflows/size.yml
  packages/message-compiler/package.json
  rollup.config.js
Labels: Type: Improvement

#621 Improvement: revise message format explorer
  format-explorer/README.md
  format-explorer/package.json
  format-explorer/src/index.css
  format-explorer/src/shim-vue.d.ts
  format-explorer/tsconfig.json
  format-explorer/webpack.config.js
  format-explorer/yarn.lock
  package.json
  packages/format-explorer/LICENSE
  packages/format-explorer/README.md
  packages/format-explorer/index.html
  packages/format-explorer/package.json
  packages/format-explorer/public/favicon.ico
  packages/format-explorer/src/App.vue
  packages/format-explorer/src/assets/.gitkeep
  packages/format-explorer/src/components/Editor.vue
  packages/format-explorer/src/components/Navigation.vue
  packages/format-explorer/src/main.ts
  packages/format-explorer/src/shims-vue.d.ts
  packages/format-explorer/src/theme.ts
  packages/format-explorer/src/utils.ts
  packages/format-explorer/src/vite-env.d.ts
  packages/format-explorer/vite.config.ts
  test-d/tsconfig.json
  yarn.lock
Labels: Type: Refactoring

#623 feat: support Vue 3.2
  package.json
  packages/size-check-petite-vue-i18n/package.json
  packages/size-check-vue-i18n/package.json
  packages/vue-i18n-core/test/__snapshots__/composer.test.ts.snap
  yarn.lock
Labels: Type: Feature

#640 added missing comma in code example in Advanced > Composition API
  docs/guide/advanced/composition.md
  docs/ja/guide/advanced/composition.md
Labels: Type: Documentation

#641 feat: support web components
  docs/.vitepress/config.js
  docs/guide/advanced/wc.md
  docs/ja/guide/advanced/wc.md
  examples/web-components/README.md
  examples/web-components/index.html
  examples/web-components/package.json
  examples/web-components/public/favicon.ico
  examples/web-components/src/App.vue
  examples/web-components/src/assets/.gitkeep
  examples/web-components/src/components/HelloBlock.ce.vue
  examples/web-components/src/components/HelloI18n.ce.vue
  examples/web-components/src/components/I18nHost.ce.vue
  examples/web-components/src/main.ts
  examples/web-components/src/shims-vue.d.ts
  examples/web-components/src/vite-env.d.ts
  examples/web-components/tsconfig.json
  examples/web-components/vite.config.ts
  examples/web-components/yarn.lock
  package.json
  packages/vue-i18n-core/src/errors.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/index.ts
  packages/vue-i18n-core/test/i18n.test.ts
  packages/vue-i18n-core/test/wc.test.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/runtime.ts
  yarn.lock
Labels: Type: Feature

#643 docs: update breaking changes section
  docs/guide/migration/breaking.md
  docs/ja/guide/migration/breaking.md
Labels: Type: Documentation

#651 fix: update 'puppeteer' to ^9.0.0 with fix installation error on Appl…
  package.json
  yarn.lock
Labels: Type: Maintenance

#655 docs: add support api mode for injection APIs
  docs/api/injection.md
Labels: Type: Documentation
