Repository intlify/vue-i18n, pull requests merged in 2021-06, with the labels that each got.

#508 feat: global type definition
  examples/type-safe/README.md
  examples/type-safe/global-type-definition/.gitignore
  examples/type-safe/global-type-definition/README.md
  examples/type-safe/global-type-definition/index.html
  examples/type-safe/global-type-definition/package.json
  examples/type-safe/global-type-definition/public/favicon.ico
  examples/type-safe/global-type-definition/src/App.vue
  examples/type-safe/global-type-definition/src/assets/logo.png
  examples/type-safe/global-type-definition/src/components/HelloWorld.vue
  examples/type-safe/global-type-definition/src/locales/en-US.json
  examples/type-safe/global-type-definition/src/locales/ja-JP.json
  examples/type-safe/global-type-definition/src/main.ts
  examples/type-safe/global-type-definition/src/shims-vue.d.ts
  examples/type-safe/global-type-definition/src/vite-env.d.ts
  examples/type-safe/global-type-definition/src/vue-i18n.d.ts
  examples/type-safe/global-type-definition/tsconfig.json
  examples/type-safe/global-type-definition/vite.config.ts
  examples/type-safe/global-type-definition/yarn.lock
  examples/type-safe/type-annotation/.gitignore
  examples/type-safe/type-annotation/README.md
  examples/type-safe/type-annotation/index.html
  examples/type-safe/type-annotation/package.json
  examples/type-safe/type-annotation/public/favicon.ico
  examples/type-safe/type-annotation/src/App.vue
  examples/type-safe/type-annotation/src/assets/logo.png
  examples/type-safe/type-annotation/src/components/GlobalScope.vue
  examples/type-safe/type-annotation/src/components/LocalScope.vue
  examples/type-safe/type-annotation/src/components/en-US.json
  examples/type-safe/type-annotation/src/locales/en-US.json
  examples/type-safe/type-annotation/src/locales/schema.ts
  examples/type-safe/type-annotation/src/main.ts
  examples/type-safe/type-annotation/src/shims-vue.d.ts
  examples/type-safe/type-annotation/tsconfig.json
  examples/type-safe/type-annotation/vite.config.ts
  examples/type-safe/type-annotation/yarn.lock
  packages/core-base/src/types/utils.ts
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/src/i18n.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/legacy.ts
  packages/vue-i18n/src/runtime.ts
  packages/vue-i18n/src/vue.d.ts
  test-d/vue-i18n/composer.test-d.ts
  test-d/vue-i18n/i18n.test-d.ts
  test-d/vue-i18n/legacy.test-d.ts
Labels: Type: Feature

#519 fix `d.ts` breaking
  package.json
Labels: Type: Bug

#522 add tsx / jsx example
  examples/tsx/.gitignore
  examples/tsx/README.md
  examples/tsx/index.html
  examples/tsx/package.json
  examples/tsx/public/favicon.ico
  examples/tsx/src/App.vue
  examples/tsx/src/components/HelloWorld.vue
  examples/tsx/src/main.ts
  examples/tsx/src/shims-vue.d.ts
  examples/tsx/src/vite-env.d.ts
  examples/tsx/tsconfig.json
  examples/tsx/vite.config.ts
  examples/tsx/yarn.lock
Labels: Type: Example

#524 fix: cannot hook at beforeUnmount/unmounted
  packages/vue-i18n/src/mixin.ts
  packages/vue-i18n/test/i18n.test.ts
Labels: Type: Bug

#526 drop node v10
  package.json
  packages/vue-i18n/test/i18n.test.ts
Labels: Type: Breaking

#532 fix: __INTLIFY_PROD_DEVTOOLS__ is not defined
  packages/core-base/src/index.ts
Labels: Type: Bug

#541 Add number formatting missing type definition
  docs/api/injection.md
  docs/ja/api/injection.md
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Documentation

#544 fix: wrong vue-i18n path config in some example projects
  examples/lazy-loading/vite/package.json
  examples/lazy-loading/vite/yarn.lock
  examples/tsx/yarn.lock
  examples/type-safe/global-type-definition/package.json
  examples/type-safe/global-type-definition/yarn.lock
  examples/type-safe/type-annotation/package.json
  examples/type-safe/type-annotation/yarn.lock
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Example

#549 Fix VueJS Syntax
  docs/guide/essentials/number.md
Labels: Type: Documentation
