Repository intlify/vue-i18n, pull requests merged in 2021-11, with the labels that each got.

#764 improvement: global injection for vue-i18n-bridge
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/i18n.ts
Labels: Type: Improvement

#773 feat(docs): add usage with Quasar CLI
  docs/guide/advanced/optimization.md
  docs/guide/advanced/sfc.md
  docs/ja/guide/advanced/optimization.md
  docs/ja/guide/advanced/sfc.md
Labels: Type: Documentation

#775 Fix typo in docs
  docs/guide/essentials/number.md
Labels: Type: Documentation

#778 docs: improve doc of fall back warinings
  docs/guide/essentials/fallback.md
Labels: Type: Documentation

#780 improvement: vue-i18n-bridge installation at nuxt-bridge
  packages/vue-i18n-core/src/i18n.ts
Labels: Type: Improvement

#784 fix(core-base): fallback interpolation should not break in runtime only (fix #768)
  packages/core-base/src/translate.ts
  packages/core-base/test/translate.test.ts
Labels: Type: Bug

#799 fix: typescript errors with vue-tsc on vue-i18n-bridge
  docs/guide/migration/ways.md
  package.json
  packages/vue-i18n-core/src/i18n.ts
  scripts/build.sh
  scripts/postprocess.ts
Labels: Type: Bug

#806 fix: merge global resources of i18n custom block
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/mixins/next.ts
  packages/vue-i18n-core/src/utils.ts
  packages/vue-i18n-core/test/i18n.test.ts
Labels: Type: Bug

#811 feat: backport build-in components to vue-i18n-bridge from vue-i18n-next
  docs/guide/migration/ways.md
  e2e/bridge/components/datetime-format.test.js
  e2e/bridge/components/number-format.test.js
  e2e/bridge/components/translation.test.js
  examples/bridge/composition/components/datetime-format.html
  examples/bridge/composition/components/number-format.html
  examples/bridge/composition/components/translation.html
  packages/vue-i18n-bridge/src/index.ts
  packages/vue-i18n-bridge/src/runtime.ts
  packages/vue-i18n-core/src/components/DatetimeFormat.ts
  packages/vue-i18n-core/src/components/NumberFormat.ts
  packages/vue-i18n-core/src/components/Translation.ts
  packages/vue-i18n-core/src/components/formatRenderer.ts
  packages/vue-i18n-core/src/components/utils.ts
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/plugin/bridge.ts
  packages/vue-i18n-core/src/plugin/index.ts
  packages/vue-i18n-core/src/plugin/next.ts
  packages/vue-i18n-core/src/plugin/types.ts
  packages/vue-i18n-core/src/utils.ts
  packages/vue-i18n-core/test/plugin.test.ts
  rollup.config.js
Labels: Type: Feature
