Repository intlify/vue-i18n, pull requests merged in 2021-02, with the labels that each got.

#330 fix won't fallback when `fallbackLocale` is empty string, and add a test
  packages/core-base/src/context.ts
  packages/core-base/test/context.test.ts
Labels: Type: Bug

#332 fix: support vue-devtools component inspector custom tags breaking change
  package.json
  packages/vue-i18n/package.json
  packages/vue-i18n/src/devtools.ts
  yarn.lock
Labels: Type: Improvement

#334 fix for function `mergeLocaleMessage`, and modify some tests
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/test/composer.test.ts
  packages/vue-i18n/test/i18n.test.ts
  packages/vue-i18n/test/legacy.test.ts
Labels: Type: Bug

#342 fix: feature flags
  packages/vue-i18n/src/i18n.ts
Labels: Type: Bug

#345 fix: convert Set with Array.from
  packages/message-compiler/src/transformer.ts
Labels: Type: Improvement

#346 Support vetur component data
  packages/vue-i18n/package.json
  packages/vue-i18n/vetur/attributes.json
  packages/vue-i18n/vetur/tags.json
Labels: Type: Improvement

#353 Ignore debug.log file that create by vscode
  .gitignore
Labels: Type: Maintenance

#354 Fix typo in breaking.md
  docs/guide/migration/breaking.md
Labels: Type: Documentation

#357 fix: cannot apply custom pluralization rules
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/src/mixin.ts
  packages/vue-i18n/test/composer.test.ts
  packages/vue-i18n/test/helper.ts
  packages/vue-i18n/test/i18n.test.ts
  packages/vue-i18n/test/legacy.test.ts
Labels: Type: Bug

#362 update example project vite version to ^2.0.2
  examples/lazy-loading/vite/package.json
  examples/lazy-loading/vite/src/i18n.ts
  examples/lazy-loading/vite/yarn.lock
Labels: Type: Example

#365 fix: undefind setter using
  packages/vue-i18n/src/composer.ts
  packages/vue-i18n/src/mixin.ts
Labels: Type: Bug

#368 improvement: upgrade vue devtools
  packages/vue-i18n/package.json
  packages/vue-i18n/src/devtools.ts
  yarn.lock
Labels: Type: Improvement
