Repository intlify/vue-i18n, pull requests merged in 2021-09, with the labels that each got.

#661 docs: fix typo dat"a"TimeFormats
  docs/guide/migration/breaking.md
Labels: Type: Documentation

#664 Fixed a type in the Composition API documentation (it's -> its)
  docs/guide/advanced/composition.md
Labels: Type: Documentation

#673 feat: export types
  packages/vue-i18n-core/src/index.ts
Labels: Type: Feature

#676 feat: bridge for vue-i18n@v8.26.1 or later
  docs/.vitepress/config.js
  docs/guide/migration/composition.md
  docs/guide/migration/ways.md
  docs/installation.md
  docs/ja/guide/migration/composition.md
  docs/ja/guide/migration/ways.md
  e2e/bridge/basic.test.js
  e2e/bridge/component.test.js
  e2e/bridge/plural.test.js
  e2e/bridge/scope/global.test.js
  e2e/bridge/scope/inherit-locale.test.js
  e2e/bridge/scope/local.test.js
  examples/bridge/composition/basic.html
  examples/bridge/composition/component.html
  examples/bridge/composition/plural.html
  examples/bridge/composition/scope/global.html
  examples/bridge/composition/scope/inherit-locale.html
  examples/bridge/composition/scope/local.html
  examples/bridge/legacy/basic.html
  examples/bridge/legacy/component.html
  examples/bridge/legacy/plural.html
  examples/bridge/legacy/scope/global.html
  examples/bridge/legacy/scope/inherit-locale.html
  examples/bridge/legacy/scope/local.html
  jest.config.js
  package.json
  packages/core-base/src/context.ts
  packages/core-base/src/datetime.ts
  packages/core-base/src/number.ts
  packages/core-base/src/translate.ts
  packages/global.d.ts
  packages/vue-i18n-bridge/LICENSE
  packages/vue-i18n-bridge/README.md
  packages/vue-i18n-bridge/api-extractor.json
  packages/vue-i18n-bridge/index.js
  packages/vue-i18n-bridge/package.json
  packages/vue-i18n-bridge/src/index.ts
  packages/vue-i18n-bridge/src/runtime.ts
  packages/vue-i18n-bridge/src/vue.d.ts
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/errors.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/legacy.ts
  packages/vue-i18n-core/src/mixins/bridge.ts
  packages/vue-i18n-core/src/mixins/next.ts
  packages/vue-i18n-core/src/plugin.ts
  packages/vue-i18n-core/src/symbols.ts
  packages/vue-i18n-core/src/utils.ts
  packages/vue-i18n-core/src/warnings.ts
  packages/vue-i18n-core/test/composer.test.ts
  packages/vue-i18n-core/test/utils.test.ts
  rollup.config.js
  yarn.lock
Labels: Type: Feature

#691 Fix typo in docs/guide/migration/breaking.md
  docs/guide/migration/breaking.md
Labels: Type: Documentation

#696 fix: __INTLIFY_META__ access error in vue-i18n-bridge
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/utils.ts
Labels: Type: Bug

#700 improvement: expose type casting API for Legacy mode
  docs/guide/migration/ways.md
  jest.config.js
  packages/vue-i18n-bridge/README.md
  packages/vue-i18n-bridge/src/index.ts
  packages/vue-i18n-bridge/src/runtime.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/index.ts
  packages/vue-i18n-core/test/i18n.test.ts
  packages/vue-i18n/test/.gitkeep
Labels: Type: Improvement

#704 Fix typo `Stdio` for `Studio`
  docs/guide/advanced/typescript.md
Labels: Type: Documentation

#705 improvement: flag for vue-i18n-bridge
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/legacy.ts
  packages/vue-i18n-core/src/mixins/bridge.ts
  packages/vue-i18n-core/src/symbols.ts
  packages/vue-i18n-core/test/i18n.test.ts
Labels: Type: Improvement

#709 improvement: support vue-i18n-loader bridge mode
  packages/vue-i18n-core/src/mixins/bridge.ts
Labels: Type: Improvement
