Repository intlify/vue-i18n, pull requests merged in 2022-01, with the labels that each got.

#861 improvement: export castToVueI18n for @intlity/vue-i18n-bridge
  packages/petite-vue-i18n/src/index.ts
  packages/petite-vue-i18n/src/runtime.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/runtime.ts
Labels: Type: Improvement

#862 docs: add scope resolving section
  docs/guide/advanced/component.md
  docs/guide/essentials/datetime.md
  docs/guide/essentials/number.md
  docs/ja/guide/advanced/component.md
  docs/ja/guide/essentials/datetime.md
  docs/ja/guide/essentials/number.md
Labels: Type: Documentation

#863 docs: fix typo in word
  docs/guide/advanced/component.md
Labels: Type: Documentation

#869 docs: fix typos
  docs/guide/advanced/typescript.md
Labels: Type: Documentation

#876 fix: null access on mount hook
  packages/vue-i18n-core/src/mixins/next.ts
Labels: Type: Improvement

#879 fix: null element access
  packages/vue-i18n-core/src/mixins/next.ts
Labels: Type: Improvement

#891 example: back-end integration and i18n resources compilation
  examples/backend/.gitignore
  examples/backend/README.md
  examples/backend/db/en.json
  examples/backend/db/ja.json
  examples/backend/db/message.d.ts
  examples/backend/index.html
  examples/backend/package.json
  examples/backend/public/favicon.ico
  examples/backend/scripts/generate.ts
  examples/backend/src/App.vue
  examples/backend/src/assets/logo.png
  examples/backend/src/constants.ts
  examples/backend/src/env.d.ts
  examples/backend/src/locales.ts
  examples/backend/src/main.ts
  examples/backend/tsconfig.json
  examples/backend/vite.config.ts
  pnpm-lock.yaml
Labels: Type: Example

#897 improve types declaration
  packages/vue-i18n-core/src/i18n.ts
  test-d/vue-i18n/i18n.test-d.ts
Labels: Type: Bug

#903 fix: revert type test case change in strictI18n
  test-d/vue-i18n/i18n.test-d.ts
Labels: Type: Improvement

#907 fix: avoid undefined read
  packages/vue-i18n-core/src/mixins/next.ts
Labels: Type: Improvement
