Repository intlify/vue-i18n, pull requests merged in 2022-04, with the labels that each got.

#972 fix(components): strictly slot rendering
  packages/vue-i18n-core/src/components/formatRenderer.ts
  packages/vue-i18n-core/test/__snapshots__/issues.test.ts.snap
  packages/vue-i18n-core/test/issues.test.ts
Labels: Type: Bug

#973 fix(bridge): improvement writable install function for vue-i18n-routing
  packages/vue-i18n-core/src/i18n.ts
Labels: Type: Improvement

#974 feat: change `globalInjection` option default value
  docs/guide/advanced/composition.md
  docs/ja/guide/advanced/composition.md
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/test/issues.test.ts
Labels: Type: Feature

#977 feat: release global scope
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/test/i18n.test.ts
Labels: Type: Improvement

#982 fix: link to vite-plugin-vue-i18n
  docs/guide/advanced/optimization.md
Labels: Type: Documentation

#983 fix(legacy): allow multi legacy i18n instance for bridge
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/warnings.ts
Labels: Type: Improvement
