Repository intlify/vue-i18n, pull requests merged in 2022-08, with the labels that each got.

#1041 replace docs site with vitepress v1
  docs/.ja/api/component.md
  docs/.ja/api/composition.md
  docs/.ja/api/directive.md
  docs/.ja/api/general.md
  docs/.ja/api/injection.md
  docs/.ja/api/legacy.md
  docs/.ja/ecosystem/integrations.md
  docs/.ja/ecosystem/official.md
  docs/.ja/ecosystem/tools.md
  docs/.ja/guide/advanced/component.md
  docs/.ja/guide/advanced/composition.md
  docs/.ja/guide/advanced/directive.md
  docs/.ja/guide/advanced/function.md
  docs/.ja/guide/advanced/lazy.md
  docs/.ja/guide/advanced/optimization.md
  docs/.ja/guide/advanced/sfc.md
  docs/.ja/guide/advanced/typescript.md
  docs/.ja/guide/advanced/wc.md
  docs/.ja/guide/essentials/datetime.md
  docs/.ja/guide/essentials/fallback.md
  docs/.ja/guide/essentials/local.md
  docs/.ja/guide/essentials/number.md
  docs/.ja/guide/essentials/pluralization.md
  docs/.ja/guide/essentials/scope.md
  docs/.ja/guide/essentials/syntax.md
  docs/.ja/guide/index.md
  docs/.ja/guide/migration/breaking.md
  docs/.ja/guide/migration/features.md
  docs/.ja/guide/migration/vue2.md
  docs/.ja/guide/migration/vue3.md
  docs/.ja/index.md
  docs/.ja/installation.md
  docs/.ja/introduction.md
  docs/.ja/v8-docs.md
  docs/.vitepress/config.js
  docs/.vitepress/config.ts
  docs/.vitepress/theme/Layout.vue
  docs/.vitepress/theme/components/AsideSponsors.vue
  docs/.vitepress/theme/components/HomeSponsors.vue
  docs/.vitepress/theme/components/Sponsor.vue
  docs/.vitepress/theme/composables/sponsor.ts
  docs/.vitepress/theme/index.ts
  docs/.vitepress/theme/sponsor.ts
  docs/.vitepress/theme/sponsors.json
  docs/.vitepress/theme/styles/global.css
  docs/guide/advanced/optimization.md
  docs/guide/essentials/fallback.md
  docs/guide/essentials/syntax.md
  docs/guide/installation.md
  docs/guide/introduction.md
  docs/guide/migration/vue2.md
  docs/guide/v8-docs.md
  docs/index.md
  docs/introduction.md
  docs/public/vue-i18n-logo.svg
  netlify.toml
  package.json
  pnpm-lock.yaml
Labels: Status: In Progress, Type: Documentation

#1094 Fix documentation typography
  docs/.vitepress/config.ts
Labels: Type: Documentation

#1097 Fix(docs): Fixing Typo in optimization.md
  docs/guide/advanced/optimization.md
Labels: Type: Documentation

#1098 Editorial fix
  docs/.ja/guide/advanced/typescript.md
  docs/guide/advanced/typescript.md
Labels: Type: Documentation

#1099 Editorial fixes
  docs/.ja/guide/advanced/typescript.md
  docs/.ja/guide/advanced/wc.md
  docs/guide/advanced/typescript.md
  docs/guide/advanced/wc.md
Labels: Type: Documentation

#1100 Editorial fixes
  packages/petite-vue-i18n/README.md
Labels: Type: Documentation

#1105 i18n.global.locale is a ref
  docs/guide/essentials/scope.md
Labels: Type: Documentation

#1106 fix(typo): update IE note on date formatting section
  docs/.ja/guide/essentials/datetime.md
  docs/guide/essentials/datetime.md
Labels: Type: Documentation

#1108 fix: scope execution context resolving
  examples/ssr/vite/server.js
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/directive.ts
Labels: Type: Bug

#1110 fix: conflict process global object in vDirective function
  packages/vue-i18n-core/src/directive.ts
Labels: Type: Bug

#1129 Add information about the pluralization option for the Composition API
  docs/guide/essentials/pluralization.md
Labels: Type: Documentation

#1137 feat: support ESM file extension
  package.json
  packages/core-base/package.json
  packages/core/package.json
  packages/devtools-if/package.json
  packages/message-compiler/package.json
  packages/petite-vue-i18n/package.json
  packages/shared/package.json
  packages/size-check-core/vite.config.ts
  packages/size-check-petite-vue-i18n/src/main.ts
  packages/size-check-petite-vue-i18n/vite.config.ts
  packages/size-check-vue-i18n/src/main.ts
  packages/size-check-vue-i18n/vite.config.ts
  packages/vue-devtools/package.json
  packages/vue-i18n-bridge/package.json
  packages/vue-i18n-core/package.json
  packages/vue-i18n-core/test/helper.ts
  packages/vue-i18n/package.json
  pnpm-lock.yaml
  rollup.config.js
  tsconfig.json
Labels: Type: Feature

#1140 improvement: remove feature flag warning
  packages/vue-i18n-core/src/misc.ts
Labels: Type: Improvement

#1147 feat: cjs/mjs file extension fully
  package.json
  packages/core-base/index.js
  packages/core-base/index.mjs
  packages/core-base/package.json
  packages/core/index.js
  packages/core/index.mjs
  packages/core/package.json
  packages/devtools-if/index.js
  packages/devtools-if/index.mjs
  packages/devtools-if/package.json
  packages/message-compiler/index.js
  packages/message-compiler/index.mjs
  packages/message-compiler/package.json
  packages/petite-vue-i18n/index.js
  packages/petite-vue-i18n/index.mjs
  packages/petite-vue-i18n/package.json
  packages/shared/index.js
  packages/shared/index.mjs
  packages/shared/package.json
  packages/vue-devtools/index.js
  packages/vue-devtools/index.mjs
  packages/vue-devtools/package.json
  packages/vue-i18n-bridge/index.js
  packages/vue-i18n-bridge/index.mjs
  packages/vue-i18n-bridge/package.json
  packages/vue-i18n-core/index.js
  packages/vue-i18n-core/index.mjs
  packages/vue-i18n-core/package.json
  packages/vue-i18n/index.js
  packages/vue-i18n/index.mjs
  packages/vue-i18n/package.json
  pnpm-lock.yaml
  rollup.config.js
  scripts/build.ts
  scripts/fixpack.ts
  scripts/utils.ts
Labels: Type: Feature

#1152 fix: module wrong exportings
  packages/core-base/package.json
  packages/core/package.json
  packages/devtools-if/package.json
  packages/message-compiler/package.json
  packages/petite-vue-i18n/package.json
  packages/shared/package.json
  packages/vue-devtools/package.json
  packages/vue-i18n-bridge/package.json
  packages/vue-i18n/package.json
Labels: Type: Bug
