Repository intlify/vue-i18n, pull requests merged in 2022-03, with the labels that each got.

#940 feat: Support `useI18n` for Legacy API mode
  e2e/composition.test.js
  examples/legacy/composition.html
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/errors.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/test/i18n.test.ts
Labels: Type: Feature

#945 fix: linked message fallbacking
  packages/core-base/src/context.ts
  packages/core-base/src/runtime.ts
  packages/core-base/src/translate.ts
  packages/core-base/test/translate.test.ts
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/test/issues.test.ts
Labels: Type: Bug

#954 fix: nullish assignment
  packages/vue-i18n-core/src/errors.ts
  packages/vue-i18n-core/src/i18n.ts
Labels: Type: Bug

#956 docs: add composition api migration from legacy api
  docs/guide/migration/ways.md
  docs/ja/guide/migration/ways.md
Labels: Type: Documentation

#965 fix: resolve default message value
  packages/core-base/src/translate.ts
  packages/vue-i18n-core/test/issues.test.ts
Labels: Type: Bug

#969 docs (composition): typos, duplication
  docs/guide/advanced/composition.md
Labels: Type: Documentation
