Repository intlify/vue-i18n, pull requests merged in 2022-07, with the labels that each got.

#1043 fix typo and polish
  docs/guide/essentials/syntax.md
  packages/message-compiler/src/generator.ts
  packages/vue-i18n-core/src/composer.ts
Labels: Type: Improvement

#1046 docs: add missing imports and fix typescript example of vue-i18n-bridge
  packages/vue-i18n-bridge/README.md
Labels: Type: Documentation

#1050 Fix spelling
  docs/guide/migration/vue3.md
Labels: Type: Documentation

#1057 fix: cannot modulo parse hangup
  packages/message-compiler/src/tokenizer.ts
  packages/message-compiler/test/__snapshots__/compiler.test.ts.snap
  packages/message-compiler/test/compiler.test.ts
  packages/message-compiler/test/parser/__snapshots__/modulo.test.ts.snap
  packages/message-compiler/test/parser/modulo.test.ts
  packages/message-compiler/test/tokenizer/__snapshots__/named.test.ts.snap
  packages/message-compiler/test/tokenizer/named.test.ts
  packages/vue-i18n-core/test/__snapshots__/issues.test.ts.snap
  packages/vue-i18n-core/test/issues.test.ts
Labels: Type: Bug

#1064 fix: slot resolving in render function
  packages/vue-i18n-core/src/components/Translation.ts
Labels: Type: Improvement

#1071 fix(vue-i18n-bridge): install error cause by peer deps
  packages/vue-i18n-bridge/package.json
Labels: Type: Bug

#1076 fix: lifecycle hook context binding
  examples/bridge/composition/scope/local.html
  packages/vue-i18n-core/src/i18n.ts
Labels: Type: Bug

#1084 Added pluralization example to custom directive page
  docs/guide/advanced/directive.md
Labels: Type: Documentation

#1086 fix: v-t directive reactivity
  packages/vue-i18n-core/src/directive.ts
  packages/vue-i18n-core/test/issues.test.ts
Labels: Type: Bug

#1087 feat: support SSR for v-t
  packages/vue-i18n-core/src/directive.ts
  packages/vue-i18n-core/test/ssr.test.ts
Labels: Type: Feature
