Repository intlify/vue-i18n, pull requests merged in 2022-05, with the labels that each got.

#997 improvement: esm-bundler warning
  docs/guide/advanced/optimization.md
  jest.config.js
  packages/global.d.ts
  packages/size-check-vue-i18n/rollup.config.js
  packages/vue-i18n/README.md
  packages/vue-i18n/src/misc.ts
  rollup.config.js
Labels: Type: Improvement

#1005 docs: Update vue3.md
  docs/guide/migration/vue3.md
Labels: Type: Documentation

#1017 fix: number & datetime format options
  packages/core-base/src/datetime.ts
  packages/core-base/src/number.ts
  packages/core-base/test/datetime.test.ts
  packages/core-base/test/number.test.ts
  packages/vue-i18n-core/test/composer.test.ts
Labels: Type: Bug
