Repository intlify/vue-i18n, pull requests merged in 2022-11, with the labels that each got.

#1221 fix(docs): add more unplugin-vue-i18n docs and tweak some sections
  docs/guide/advanced/optimization.md
  docs/guide/advanced/sfc.md
Labels: Type: Documentation

#1222 feat: export `$te` as global on composition mode
  docs/api/injection.md
  packages/petite-vue-i18n/src/vue.d.ts
  packages/vue-i18n-bridge/src/vue.d.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Feature

#1227 docs: update introduction
  docs/guide/index.md
Labels: Type: Documentation

#1237 fix: exntending for Composer and VueI18n
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/mixins/next.ts
  packages/vue-i18n-core/test/helper.ts
  packages/vue-i18n-core/test/i18n.test.ts
Labels: Type: Improvement

#1236 fix: correct typo in `TranslateVNodeSymbol`
  packages/vue-i18n-core/src/components/Translation.ts
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/symbols.ts
  packages/vue-i18n-core/test/__snapshots__/composer.test.ts.snap
  packages/vue-i18n-core/test/composer.test.ts
Labels: Type: Improvement

#1239 fix: multiple VueI18n extending
  packages/vue-i18n-core/src/mixins/next.ts
  packages/vue-i18n-core/test/i18n.test.ts
Labels: Type: Bug

#1241 fix: avoid VueI18n extending on root
  packages/vue-i18n-core/src/mixins/next.ts
Labels: Type: Bug

#1245 Docs: search for "useI18n" yields non-existing /ja/api/composition.html
  docs/.vitepress/config.ts
Labels: Type: Documentation
