Repository intlify/vue-i18n, pull requests merged in 2022-12, with the labels that each got.

#1261 feat(shared): sharable symbol
  packages/shared/src/utils.ts
  packages/shared/test/utils.test.ts
Labels: Type: Feature

#1275 docs: update links
  docs/.ja/guide/advanced/component.md
  docs/.ja/guide/migration/breaking.md
  docs/guide/advanced/component.md
  docs/guide/integrations/nuxt3.md
  docs/guide/migration/breaking.md
  examples/frameworks/nuxt3/README.md
  examples/frameworks/nuxt3/nuxt.config.ts
  examples/frameworks/nuxt3/tsconfig.json
Labels: Type: Documentation

#1266 Fixed Links, added up-to-date link to v3 docs
  docs/guide/integrations/nuxt3.md
Labels: Type: Documentation

#1277 fix: update typescript version and fix type error
  package.json
  packages/core-base/src/context.ts
  packages/core-base/src/datetime.ts
  packages/core-base/src/number.ts
  packages/core-base/src/runtime.ts
  packages/core-base/src/translate.ts
  packages/shared/src/utils.ts
  packages/vue-i18n-core/src/components/DatetimeFormat.ts
  packages/vue-i18n-core/src/components/NumberFormat.ts
  packages/vue-i18n-core/src/components/Translation.ts
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/legacy.ts
  packages/vue-i18n-core/src/mixins/bridge.ts
  packages/vue-i18n-core/src/utils.ts
  packages/vue-i18n-core/test/__snapshots__/composer.test.ts.snap
  packages/vue-i18n-core/test/__snapshots__/i18n.test.ts.snap
  packages/vue-i18n-core/test/diretive.test.ts
  packages/vue-i18n-core/test/helper.ts
  packages/vue-i18n-core/test/i18n.test.ts
  packages/vue-i18n-core/test/mixin.test.ts
  pnpm-lock.yaml
Labels: Type: Improvement
