Repository intlify/vue-i18n, pull requests merged in 2022-06, with the labels that each got.

#1022 improvement: allow custom block `useI18n` on Legacy API mode
  packages/vue-i18n-core/src/errors.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/test/i18n.test.ts
Labels: Type: Improvement

#1023 fix: improvement processor for linked and pluralization
  e2e/bridge/components/datetime-format.test.js
  e2e/components/datetime-format.test.js
  e2e/datetime.test.js
  jest.e2e.config.js
  packages/core-base/src/context.ts
  packages/core-base/src/runtime.ts
  packages/core-base/test/helper.ts
  packages/core-base/test/translate.test.ts
  packages/message-compiler/src/generator.ts
  packages/message-compiler/src/transformer.ts
  packages/message-compiler/test/__snapshots__/compiler.test.ts.snap
  packages/message-compiler/test/__snapshots__/generator.test.ts.snap
  packages/message-compiler/test/__snapshots__/transformer.test.ts.snap
  packages/message-compiler/test/generator.test.ts
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/test/__snapshots__/issues.test.ts.snap
  packages/vue-i18n-core/test/issues.test.ts
  packages/vue-i18n-core/test/legacy.test.ts
Labels: Type: Bug

#1028 docs: typo
  docs/guide/advanced/optimization.md
  docs/guide/advanced/sfc.md
Labels: Type: Documentation

#1032 docs: typo
  docs/guide/essentials/fallback.md
Labels: Type: Documentation

#1037 fix postTranslation option
  packages/core-base/src/context.ts
  packages/core-base/src/translate.ts
  packages/core-base/test/translate.test.ts
  packages/vue-i18n-core/test/composer.test.ts
Labels: Type: Bug

#1039 fix: typo in the layout slot
  docs/.vitepress/theme/Layout.vue
Labels: Type: Documentation

#1040 fix: fix isExist always returns false and polish build.ts
  scripts/build.ts
Labels: Type: Refactoring
