Repository intlify/vue-i18n, pull requests merged in 2023-01, with the labels that each got.

#1306 fix: generate ComponentCustomProperties d.ts
  scripts/release.sh
Labels: Type: Bug

#1309 fix: useI18n wrong type and other type broken
  packages/core-base/src/context.ts
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/legacy.ts
  pnpm-lock.yaml
  test-d/core-base/runtime.test-d.ts
  test-d/vue-i18n/i18n.test-d.ts
Labels: Type: Bug

#1311 docs: @huntersofbook/i18n tools
  docs/ecosystem/tools.md
Labels: Type: Documentation

#1310 fix: support type inference of Translation, NumberFormat and DatetimeFormat components on SFC template and JSX/TSX
  .github/workflows/ci.yml
  jest.config.js
  jest.global.setup.js
  package.json
  packages/vue-i18n-bridge/src/index.ts
  packages/vue-i18n-bridge/src/runtime.ts
  packages/vue-i18n-bridge/src/vue.d.ts
  packages/vue-i18n-core/src/components/DatetimeFormat.ts
  packages/vue-i18n-core/src/components/NumberFormat.ts
  packages/vue-i18n-core/src/components/Translation.ts
  packages/vue-i18n-core/src/components/index.ts
  packages/vue-i18n-core/src/index.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/runtime.ts
  packages/vue-i18n/src/vue.d.ts
  scripts/build.sh
  test-dts/core-base/context.test-d.ts
  test-dts/core-base/datetime.test-d.ts
  test-dts/core-base/number.test-d.ts
  test-dts/core-base/runtime.test-d.ts
  test-dts/core-base/translate.test-d.ts
  test-dts/index.d.ts
  test-dts/schema.ts
  test-dts/tsconfig.json
  test-dts/vue-i18n/components.test-d.tsx
  test-dts/vue-i18n/composer.test-d.ts
  test-dts/vue-i18n/i18n.test-d.ts
  test-dts/vue-i18n/legacy.test-d.ts
  tsconfig.json
Labels: Type: Improvement

#1313 fix: support pascal case for components
  packages/vue-i18n-bridge/src/vue.d.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Improvement

#1319 fix: upgrade rollup v3
  .gitignore
  package.json
  pnpm-lock.yaml
  rollup.config.mjs
Labels: Type: Maintenance

#1316 fix: global locale is not respected by useI18n
  e2e/composition.test.js
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/test/i18n.test.ts
Labels: Type: Improvement
