Repository intlify/vue-i18n, pull requests merged in 2023-09, with the labels that each got.

#1519 fix: typo jit compilation warning message
  packages/core-base/src/compilation.ts
Labels: Type: Refactoring

#1527 feat(shared): support dist package for browser
  packages/shared/package.json
Labels: Type: Feature

#1531 fix: optimize tree-shaking for devtools packages
  packages/core-base/package.json
  packages/devtools-if/src/index.ts
  packages/vue-i18n/package.json
  pnpm-lock.yaml
Labels: Type: Improvement

#1532 improvement: tweak compler registration and message condition on compile function
  packages/core-base/src/compilation.ts
  packages/core/package.json
  packages/core/src/index.ts
  packages/global.d.ts
  packages/petite-vue-i18n/src/index.ts
  packages/vue-i18n-bridge/src/index.ts
  packages/vue-i18n/src/index.ts
Labels: Type: Improvement

#1536 fix(vue-i18n-bridge): peer dependency warning
  packages/vue-i18n-bridge/package.json
  pnpm-lock.yaml
Labels: Type: Bug

#1544 chore: fix release with latest tag
  scripts/release.sh
Labels: Type: Maintenance

#1548 docs: add build.transpile option
  docs/guide/integrations/nuxt3.md
Labels: Type: Documentation

#1550 fix: cannot resolve linked refer message that has hypen
  packages/vue-i18n-core/test/issues.test.ts
Labels: Type: Bug

#1551 fix: type errors for core-base
  packages/core-base/src/context.ts
  packages/core-base/src/devtools.ts
  packages/core-base/src/runtime.ts
Labels: Type: Bug

#1554 Handle falsy values in i18n.te()
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/test/composer.test.ts
Labels: Type: Bug

#1565 docs: fix typo in optimization.md
  docs/guide/advanced/optimization.md
Labels: Type: Documentation

#1566 feat(core-base): support locale detector
  packages/core-base/src/context.ts
  packages/core-base/src/datetime.ts
  packages/core-base/src/fallbacker.ts
  packages/core-base/src/number.ts
  packages/core-base/src/runtime.ts
  packages/core-base/src/translate.ts
  packages/core-base/test/translate.test.ts
Labels: Type: Feature

#1571 fix(core-base): wrong list index resolving on jit optimization
  packages/core-base/src/format.ts
  packages/core-base/test/compilation.test.ts
Labels: Type: Bug

#1572 Fix typos in breaking.md doc
  docs/guide/migration/breaking.md
Labels: Type: Documentation

#1573 fix: support runtime module for node.js
  docs/guide/installation.md
  packages/core/README.md
  packages/vue-i18n/README.md
  rollup.config.mjs
Labels: Type: Bug
