Repository intlify/vue-i18n, pull requests merged in 2023-11, with the labels that each got.

#1624 fix: wrong source getting
  packages/core-base/src/translate.ts
Labels: Type: Bug

#1628 fix: Nuxt I18n type inference
  packages/vue-i18n-bridge/src/vue.d.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Bug

#1635 feat: export message merging utilities to shared module
  packages/shared/src/index.ts
  packages/shared/src/messages.ts
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/mixins/bridge.ts
  packages/vue-i18n-core/src/utils.ts
Labels: Type: Feature

#1639 fix: tweak `@intlify/core` conditional exports
  packages/core/package.json
Labels: Type: Improvement
