Repository intlify/vue-i18n, pull requests merged in 2023-08, with the labels that each got.

#1479 fix: cleanup global injection resources
  packages/vue-i18n-core/src/i18n.ts
Labels: Type: Bug

#1488 feat!: replace algolia with local search
  docs/.vitepress/config.mts
  package.json
  pnpm-lock.yaml
Labels: Type: Documentation

#1492 fix(guide): typo resourece -> resource
  docs/guide/advanced/optimization.md
Labels: Type: Documentation

#1490 docs: diff with syntax highlighting in nuxt integration
  docs/guide/integrations/nuxt3.md
Labels: Type: Documentation

#1494 fix: improve custom extender
  packages/petite-vue-i18n/src/index.ts
  packages/petite-vue-i18n/src/runtime.ts
  packages/vue-i18n-bridge/src/index.ts
  packages/vue-i18n-bridge/src/runtime.ts
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/index.ts
  packages/vue-i18n-core/src/legacy.ts
  packages/vue-i18n-core/src/mixins/next.ts
  packages/vue-i18n-core/src/symbols.ts
  packages/vue-i18n-core/src/types.ts
  packages/vue-i18n-core/test/i18n.test.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/runtime.ts
Labels: Type: Improvement

#1495 fix: drop componentInstanceCreatedListener
  docs/.ja/api/legacy.md
  packages/petite-vue-i18n/src/index.ts
  packages/petite-vue-i18n/src/runtime.ts
  packages/vue-i18n-bridge/src/index.ts
  packages/vue-i18n-bridge/src/runtime.ts
  packages/vue-i18n-core/src/index.ts
  packages/vue-i18n-core/src/legacy.ts
  packages/vue-i18n-core/src/mixins/next.ts
  packages/vue-i18n-core/test/i18n.test.ts
  packages/vue-i18n-core/test/mixin.test.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/runtime.ts
Labels: Type: Refactoring

#1499 docs: add vite-plugin-vue-i18n support vite version to warning notice
  docs/guide/advanced/optimization.md
Labels: Type: Documentation

#1497 feat: support custom message format with `messageCompiler` option
  docs/.vitepress/config.mts
  docs/guide/advanced/format.md
  examples/message-format/README.md
  examples/message-format/index.html
  examples/message-format/package.json
  examples/message-format/public/vite.svg
  examples/message-format/src/App.vue
  examples/message-format/src/compilation.ts
  examples/message-format/src/components/HelloWorld.vue
  examples/message-format/src/main.ts
  examples/message-format/src/style.css
  examples/message-format/src/vite-env.d.ts
  examples/message-format/tsconfig.json
  examples/message-format/tsconfig.node.json
  examples/message-format/vite.config.ts
  packages/core-base/src/compilation.ts
  packages/core-base/src/context.ts
  packages/core-base/src/errors.ts
  packages/core-base/src/runtime.ts
  packages/core-base/src/translate.ts
  packages/core-base/src/warnings.ts
  packages/core-base/test/compilation.test.ts
  packages/message-compiler/src/helpers.ts
  packages/petite-vue-i18n/src/index.ts
  packages/petite-vue-i18n/src/runtime.ts
  packages/vue-i18n-bridge/src/index.ts
  packages/vue-i18n-bridge/src/runtime.ts
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/index.ts
  packages/vue-i18n-core/test/composer.test.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/runtime.ts
  pnpm-lock.yaml
Labels: Type: Feature

#1500 fix: wrong error & warn code definition
  packages/core-base/src/context.ts
  packages/core-base/src/errors.ts
  packages/core-base/src/warnings.ts
  packages/message-compiler/src/errors.ts
  packages/message-compiler/src/generator.ts
  packages/message-compiler/src/minifier.ts
  packages/message-compiler/test/generator.test.ts
  packages/message-compiler/test/minifier.test.ts
  packages/shared/src/error.ts
  packages/shared/src/index.ts
  packages/shared/src/utils.ts
  packages/shared/src/warn.ts
  packages/shared/test/utils.test.ts
  packages/vue-i18n-core/src/errors.ts
  packages/vue-i18n-core/src/warnings.ts
Labels: Type: Refactoring

#1506 fix(message-compiler): linked modifier breaks with parenthesis
  package.json
  packages/message-compiler/src/tokenizer.ts
  packages/message-compiler/test/tokenizer/linked.test.ts
  pnpm-lock.yaml
  rollup.config.mjs
  spec/syntax.ebnf
Labels: Type: Bug

#1509 fix(core-base): `isMessageAST` more strictly
  packages/core-base/src/translate.ts
  packages/core-base/test/translate.test.ts
Labels: Type: Bug

#1510 perf: support drop message compiler feature flag
  docs/guide/advanced/optimization.md
  packages/core-base/src/compilation.ts
  packages/core-base/src/misc.ts
  packages/core-base/src/translate.ts
  packages/core-base/test/compilation.test.ts
  packages/core-base/test/translate.test.ts
  packages/global.d.ts
  packages/size-check-core/vite.config.ts
  packages/size-check-petite-vue-i18n/vite.config.ts
  packages/size-check-vue-i18n/vite.config.ts
  packages/vue-i18n-core/src/misc.ts
  packages/vue-i18n/README.md
  rollup.config.mjs
  vitest.config.ts
Labels: Type: Feature

#1511 feat: export `v-t` directive type
  packages/vue-i18n-core/src/directive.ts
  packages/vue-i18n-core/src/index.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/runtime.ts
Labels: Type: Feature
