Repository intlify/vue-i18n, pull requests merged in 2023-07, with the labels that each got.

#1451 fix: JIT compilation on runtime only
  packages/core/src/runtime.ts
  packages/petite-vue-i18n/src/runtime.ts
  packages/vue-i18n-bridge/src/runtime.ts
  packages/vue-i18n/src/runtime.ts
Labels: Type: Bug

#1455 fix: allow AST on `rt`
  packages/core-base/src/index.ts
  packages/core-base/src/translate.ts
  packages/vue-devtools/src/index.ts
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/test/composer.test.ts
  packages/vue-i18n-core/test/legacy.test.ts
Labels: Type: Bug

#1456 perf: reduce AST size optimization
  packages/message-compiler/src/compiler.ts
  packages/message-compiler/src/nodes.ts
  packages/message-compiler/src/optimizer.ts
  packages/message-compiler/test/__snapshots__/compiler.test.ts.snap
  packages/message-compiler/test/__snapshots__/optimizer.test.ts.snap
Labels: Type: Performance

#1460 feat: node esm for message compiler
  packages/message-compiler/package.json
  packages/message-compiler/src/generator.ts
  rollup.config.mjs
Labels: Type: Feature

#1461 fix: conditional exports order for message compiler
  packages/message-compiler/package.json
  pnpm-lock.yaml
Labels: Type: Bug

#1469 Add example code for deployed app for nuxt3-app-vue-i18n
  docs/guide/integrations/nuxt3.md
Labels: Type: Documentation

#1474 feat: support AST minification
  packages/core-base/src/format.ts
  packages/core-base/test/compilation.test.ts
  packages/message-compiler/src/compiler.ts
  packages/message-compiler/src/minifier.ts
  packages/message-compiler/src/nodes.ts
  packages/message-compiler/src/options.ts
  packages/message-compiler/test/__snapshots__/compiler.test.ts.snap
  packages/message-compiler/test/__snapshots__/minifier.test.ts.snap
  packages/message-compiler/test/compiler.test.ts
  packages/message-compiler/test/minifier.test.ts
Labels: Type: Feature, Type: Performance

#1476 Fix #1475: Typo in documentation when referring to translation component
  docs/.ja/api/component.md
Labels: Type: Documentation

#1477 fix: root context message availability for linked messages in SFCs on production
  packages/vue-i18n-core/src/composer.ts
Labels: Type: Bug
