Repository intlify/vue-i18n, pull requests merged in 2023-06, with the labels that each got.

#1416 fix: Resolve the message in components which was rendered with slots, for about `<i18n-t>`, `<i18n-n>` and `<i18n-d>`
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/test/components/Translation.test.ts
  packages/vue-i18n-core/test/issues.test.ts
Labels: Type: Bug

#1418 fix: reslove with caml-case for components
  packages/vue-i18n-core/src/plugin/next.ts
  packages/vue-i18n-core/test/__snapshots__/issues.test.ts.snap
  packages/vue-i18n-core/test/issues.test.ts
  packages/vue-i18n-core/test/plugin.test.ts
Labels: Type: Bug

#1431 Update index.md
  docs/guide/index.md
Labels: Type: Documentation

#1433 fix: improve string join performance
  benchmark/compile.mjs
  benchmark/complex.mjs
  benchmark/index.mjs
  benchmark/simple.mjs
  package.json
  packages/core-base/src/runtime.ts
  packages/message-compiler/src/generator.ts
  packages/shared/src/utils.ts
  packages/shared/test/utils.test.ts
  pnpm-lock.yaml
Labels: Type: Performance
