Repository intlify/vue-i18n, pull requests merged in 2023-05, with the labels that each got.

#1394 fix: typo in I18nErrorCodes enum
  packages/vue-i18n-core/src/errors.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/test/i18n.test.ts
Labels: Type: Improvement

#1393 Fix typo
  docs/.ja/api/component.md
  packages/vue-i18n-core/src/components/base.ts
  packages/vue-i18n-core/src/components/index.ts
  packages/vue-i18n-core/src/index.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/runtime.ts
Labels: Type: Improvement

#1402 docs: add section about petite-vue-i18n
  docs/.ja/ecosystem/official.md
  docs/ecosystem/official.md
Labels: Type: Documentation

#1399 fix: drop node v14
  .github/CONTRIBUTING.md
  package.json
  packages/core-base/package.json
  packages/core/package.json
  packages/devtools-if/package.json
  packages/message-compiler/package.json
  packages/petite-vue-i18n/package.json
  packages/shared/package.json
  packages/vue-devtools/package.json
  packages/vue-i18n-bridge/package.json
  packages/vue-i18n-core/package.json
  packages/vue-i18n/package.json
Labels: Type: Improvement

#1407 feat: support vue 3.3
  examples/backend/package.json
  examples/lazy-loading/vite/package.json
  examples/ssr/vite/package.json
  examples/tsx/package.json
  examples/type-safe/global-type-definition/package.json
  examples/type-safe/type-annotation/package.json
  examples/web-components/package.json
  netlify.toml
  package.json
  packages/format-explorer/package.json
  packages/petite-vue-i18n/package.json
  packages/size-check-petite-vue-i18n/package.json
  packages/size-check-vue-i18n/package.json
  packages/vue-i18n-bridge/package.json
  packages/vue-i18n-core/package.json
  packages/vue-i18n-core/test/__snapshots__/composer.test.ts.snap
  packages/vue-i18n/package.json
  pnpm-lock.yaml
Labels: Type: Feature

#1413 fix: avoid transform to `globalThis` with bundler
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/utils.ts
Labels: Type: Improvement
