Repository intlify/vue-i18n, pull requests merged in 2024-08, with the labels that each got.

#1919 fix: vue-i18n type definition for vue package
  packages/petite-vue-i18n/src/vue.d.ts
  packages/vue-i18n-bridge/src/vue.d.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Improvement

#1914 Update ja-JP.json
  examples/type-safe/global-type-definition/src/locales/ja-JP.json
Labels: Type: Example

#1913 Update en-US.json
  examples/type-safe/global-type-definition/src/locales/en-US.json
Labels: Type: Example

#1925 Improved the global and local Scope descriptions
  docs/guide/essentials/scope.md
Labels: Type: Documentation

#1926 fix: fallback linked message params
  packages/core-base/src/runtime.ts
  packages/core-base/src/translate.ts
  packages/core-base/test/translate.test.ts
  packages/vue-i18n-core/test/issues.test.ts
Labels: Type: Bug
