Repository intlify/vue-i18n, pull requests merged in 2024-04, with the labels that each got.

#1786 fix: number and date format components not using `scope` prop
  packages/vue-i18n-core/src/components/DatetimeFormat.ts
  packages/vue-i18n-core/src/components/NumberFormat.ts
Labels: Type: Feature

#1794 fix: regression triple slash including in `.d.ts`
  rollup.config.mjs
  scripts/postprocess.ts
Labels: Type: Bug

#1795 fix: deprecate named interpolation with modulo syntax
  packages/core-base/src/compilation.ts
  packages/core-base/src/context.ts
  packages/core-base/src/errors.ts
  packages/core-base/src/warnings.ts
  packages/core-base/test/compilation.test.ts
  packages/core-base/test/errors.test.ts
  packages/core-base/test/warnings.test.ts
  packages/message-compiler/src/index.ts
  packages/message-compiler/src/nodes.ts
  packages/message-compiler/src/options.ts
  packages/message-compiler/src/parser.ts
  packages/message-compiler/src/warnings.ts
  packages/message-compiler/test/__snapshots__/compiler.test.ts.snap
  packages/message-compiler/test/compiler.test.ts
  packages/message-compiler/test/parser/__snapshots__/modulo.test.ts.snap
  packages/vue-i18n-core/src/errors.ts
  packages/vue-i18n-core/test/errors.test.ts
  packages/vue-i18n-core/test/warnings.test.ts
  rollup.config.mjs
Labels: Type: Feature, Type: Deprecated

#1797 fix: compile error for key with included hyphen in named interpolation
  packages/message-compiler/src/tokenizer.ts
  packages/message-compiler/test/tokenizer/named.test.ts
  packages/vue-i18n-core/test/issues.test.ts
  spec/syntax.ebnf
Labels: Type: Bug, 🔨 p3-minor-bug

#1799 refactor: tokenizer
  packages/message-compiler/src/tokenizer.ts
Labels: Type: Refactoring

#1798 fix: not throw warnings when using implicit fallback
  packages/core-base/src/context.ts
  packages/core-base/src/translate.ts
  packages/vue-i18n-core/test/issues.test.ts
Labels: Type: Improvement

#1800 fix: EOL announcement warning for vue-i18n-bridge
  packages/vue-i18n-core/src/misc.ts
Labels: Type: Deprecated

#1802 fix: spelling
  docs/.ja/guide/migration/breaking.md
  docs/guide/migration/breaking.md
Labels: Type: Documentation

#1801 docs: improve documentation
  docs/.vitepress/config.mts
  docs/.vitepress/theme/styles/global.css
  docs/guide/advanced/composition.md
  docs/guide/advanced/optimization.md
  docs/guide/advanced/sfc.md
  docs/guide/advanced/typescript.md
  docs/guide/advanced/wc.md
  docs/guide/essentials/datetime.md
  docs/guide/essentials/number.md
  docs/guide/essentials/scope.md
  docs/guide/essentials/started.md
  docs/guide/extra/dist.md
  docs/guide/extra/roadmap.md
  docs/guide/extra/v8-docs.md
  docs/guide/index.md
  docs/guide/installation.md
  docs/guide/integrations/nuxt3.md
  docs/guide/introduction.md
  docs/guide/migration/features.md
  docs/guide/migration/vue2.md
  examples/type-safe/global-type-definition/src/App.vue
  examples/type-safe/global-type-definition/src/components/HelloWorld.vue
  examples/type-safe/type-annotation/src/App.vue
  examples/type-safe/type-annotation/src/components/GlobalScope.vue
  examples/type-safe/type-annotation/src/components/LocalScope.vue
  examples/web-components/src/App.vue
  examples/web-components/src/components/I18nHost.ce.vue
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/legacy.ts
Labels: Type: Documentation

#1804 docs: fix dead link on menu
  docs/.vitepress/config.mts
Labels: Type: Documentation

#1813 fix(message-compiler): cannot resolve none-identifier characters at linked key
  packages/message-compiler/src/tokenizer.ts
  packages/message-compiler/test/__snapshots__/parser.test.ts.snap
  packages/message-compiler/test/__snapshots__/tokenizer.test.ts.snap
  packages/message-compiler/test/tokenizer.test.ts
  packages/vue-i18n-core/test/issues.test.ts
  spec/syntax.ebnf
Labels: Type: Bug

#1814 breaking: drop modulo syntax
  e2e/formatting/ruby.spec.ts
  examples/composition/formatting/ruby.html
  examples/legacy/formatting/ruby.html
  examples/petite/formatting/ruby.html
  packages/core-base/src/compilation.ts
  packages/core-base/src/context.ts
  packages/core-base/src/warnings.ts
  packages/core-base/test/compilation.test.ts
  packages/core-base/test/warnings.test.ts
  packages/message-compiler/src/index.ts
  packages/message-compiler/src/options.ts
  packages/message-compiler/src/parser.ts
  packages/message-compiler/src/tokenizer.ts
  packages/message-compiler/src/warnings.ts
  packages/message-compiler/test/__snapshots__/compiler.test.ts.snap
  packages/message-compiler/test/__snapshots__/tokenizer.test.ts.snap
  packages/message-compiler/test/compiler.test.ts
  packages/message-compiler/test/parser/__snapshots__/modulo.test.ts.snap
  packages/message-compiler/test/parser/modulo.test.ts
  packages/message-compiler/test/tokenizer/__snapshots__/named.test.ts.snap
  packages/message-compiler/test/tokenizer/list.test.ts
  packages/message-compiler/test/tokenizer/named.test.ts
  packages/vue-i18n-core/src/warnings.ts
  packages/vue-i18n-core/test/__snapshots__/issues.test.ts.snap
  packages/vue-i18n-core/test/issues.test.ts
  packages/vue-i18n-core/test/warnings.test.ts
  rollup.config.mjs
  spec/syntax.ebnf
Labels: Type: Breaking

#1815 fix(types): allow spyOn of "useI18n()"
  packages/vue-i18n-core/src/i18n.ts
  test-dts/vue-i18n/i18n.test-d.ts
Labels: Type: Bug

#1817 breaking: drop `allowComposition` option
  docs/guide/migration/vue3.md
  e2e/composition.spec.ts
  examples/legacy/composition.html
  packages/vue-i18n-core/src/errors.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/warnings.ts
  packages/vue-i18n-core/test/i18n.test.ts
Labels: Type: Breaking

#1823 fix: reduce devtools pkgs and size
  packages/core-base/package.json
  packages/core-base/src/context.ts
  packages/core-base/src/datetime.ts
  packages/core-base/src/devtools.ts
  packages/core-base/src/number.ts
  packages/core-base/src/translate.ts
  packages/core-base/test/devtools.test.ts
  packages/devtools-if/README.md
  packages/devtools-if/index.js
  packages/devtools-if/src/index.ts
  packages/devtools-if/test/.gitkeep
  packages/devtools-types/LICENSE
  packages/devtools-types/README.md
  packages/devtools-types/api-extractor.json
  packages/devtools-types/index.js
  packages/devtools-types/package.json
  packages/devtools-types/src/index.ts
  packages/petite-vue-i18n/package.json
  packages/vue-devtools/LICENSE
  packages/vue-devtools/README.md
  packages/vue-devtools/api-extractor.json
  packages/vue-devtools/index.js
  packages/vue-devtools/package.json
  packages/vue-devtools/src/index.ts
  packages/vue-i18n-core/package.json
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/devtools.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/legacy.ts
  packages/vue-i18n-core/src/mixins.ts
  packages/vue-i18n-core/test/i18n.test.ts
  packages/vue-i18n/package.json
  pnpm-lock.yaml
  scripts/dist-tag.sh
Labels: Type: Performance, Type: Improvement

#1825 docs: fix typos
  docs/guide/advanced/format.md
  docs/guide/advanced/typescript.md
  docs/guide/advanced/wc.md
  docs/guide/essentials/started.md
  docs/guide/integrations/nuxt3.md
Labels: Type: Documentation

#1826 breaking: drop fully `formatter` option codes on Legacy API
  docs/.ja/guide/advanced/composition.md
  docs/guide/advanced/composition.md
  docs/guide/migration/breaking.md
  packages/petite-vue-i18n/src/index.ts
  packages/petite-vue-i18n/src/runtime.ts
  packages/vue-i18n-core/src/index.ts
  packages/vue-i18n-core/src/legacy.ts
  packages/vue-i18n-core/src/warnings.ts
  packages/vue-i18n-core/test/legacy.test.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/runtime.ts
Labels: Type: Breaking

#1827 breaking: drop fully `preserveDirectiveContent` option codes on Legacy API
  docs/.ja/guide/advanced/composition.md
  docs/guide/advanced/composition.md
  docs/guide/migration/breaking.md
  packages/vue-i18n-core/src/legacy.ts
  packages/vue-i18n-core/src/warnings.ts
Labels: Type: Breaking

#1828 breaking: drop fully `preserve` modifier codes on `v-t` directive
  docs/guide/migration/breaking.md
  packages/vue-i18n-core/src/directive.ts
  packages/vue-i18n-core/src/warnings.ts
  packages/vue-i18n-core/test/diretive.test.ts
Labels: Type: Breaking

#1829 breaking: drop fully `getChoiceIndex` on Legacy API
  docs/.ja/guide/advanced/composition.md
  docs/guide/advanced/composition.md
  docs/guide/migration/breaking.md
  packages/vue-i18n-core/src/legacy.ts
  packages/vue-i18n-core/src/warnings.ts
  packages/vue-i18n-core/test/legacy.test.ts
Labels: Type: Breaking

#1832 feat!: change `$t` overloaded signature for Legacy API mode
  .github/workflows/ci.yml
  docs/.vitepress/config.mts
  docs/api/injection.md
  docs/guide/migration/breaking.md
  docs/guide/migration/breaking10.md
  docs/guide/migration/features.md
  examples/legacy/components/translation.html
  packages/petite-vue-i18n/src/vue.d.ts
  packages/vue-i18n-core/src/legacy.ts
  packages/vue-i18n-core/test/i18n.test.ts
  packages/vue-i18n-core/test/legacy.test.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Feature, Type: Breaking
