Repository intlify/vue-i18n, pull requests merged in 2024-05, with the labels that each got.

#1833 fix: remove unnecessary types from petite-vue-i18n
  packages/petite-vue-i18n/src/vue.d.ts
Labels: Type: Bug

#1837 fix: translation interface typing
  docs/api/injection.md
  docs/guide/migration/breaking10.md
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/legacy.ts
  packages/vue-i18n-core/test/i18n.test.ts
  test-dts/vue-i18n/i18n.test-d.ts
  test-dts/vue-i18n/legacy.test-d.ts
Labels: Type: Improvement

#1839 feat!: deprecate `tc` and `$tc` for Legacy API mode
  docs/api/injection.md
  docs/guide/migration/breaking10.md
  packages/vue-i18n-core/src/legacy.ts
  packages/vue-i18n-core/src/warnings.ts
  packages/vue-i18n-core/test/i18n.test.ts
  packages/vue-i18n-core/test/legacy.test.ts
  packages/vue-i18n-core/test/mixin.test.ts
  packages/vue-i18n-core/test/warnings.test.ts
Labels: Type: Deprecated

#1843 fix: Not load devtools on Node.js
  packages/core/package.json
  packages/core/src/index.ts
  packages/petite-vue-i18n/package.json
  packages/vue-i18n/package.json
  rollup.config.mjs
Labels: Type: Bug

#1844 breaking: drop translation component `<i18n>` v8.x compatibility
  packages/vue-i18n-core/src/plugin.ts
  packages/vue-i18n-core/src/plugin/next.ts
  packages/vue-i18n-core/src/plugin/types.ts
  packages/vue-i18n-core/src/warnings.ts
  packages/vue-i18n-core/test/helper.ts
  packages/vue-i18n-core/test/plugin.test.ts
  packages/vue-i18n-core/test/warnings.test.ts
Labels: Type: Breaking

#1848 docs: fix typo on vue i18n name
  docs/guide/essentials/started.md
Labels: Type: Documentation

#1849 fix: allow empty default message
  packages/core-base/src/translate.ts
  packages/core-base/test/translate.test.ts
  packages/vue-i18n-core/test/composer.test.ts
Labels: Type: Bug

#1851 perf: more bundle size optimization
  packages/core-base/src/errors.ts
  packages/core-base/src/index.ts
  packages/core-base/src/warnings.ts
  packages/core-base/test/errors.test.ts
  packages/core-base/test/warnings.test.ts
  packages/message-compiler/package.json
  packages/message-compiler/src/errors.ts
  packages/shared/src/utils.ts
  packages/shared/test/utils.test.ts
  packages/vue-i18n-core/src/errors.ts
  packages/vue-i18n-core/src/warnings.ts
  packages/vue-i18n-core/test/warnings.test.ts
Labels: Type: Performance

#1852 feat!: default enable for JIT compilation
  docs/guide/advanced/optimization.md
  docs/guide/migration/breaking10.md
  packages/core-base/src/compilation.ts
  packages/core-base/src/misc.ts
  packages/core-base/test/compilation.test.ts
  packages/core-base/test/datetime.test.ts
  packages/core-base/test/devtools.test.ts
  packages/core-base/test/number.test.ts
  packages/core-base/test/translate.test.ts
  packages/core/src/index.ts
  packages/core/src/runtime.ts
  packages/global.d.ts
  packages/petite-vue-i18n/src/index.ts
  packages/petite-vue-i18n/src/runtime.ts
  packages/size-check-core/vite.config.ts
  packages/size-check-petite-vue-i18n/vite.config.ts
  packages/size-check-vue-i18n/vite.config.ts
  packages/vue-i18n-core/src/misc.ts
  packages/vue-i18n-core/test/components/DatetimeFormat.test.ts
  packages/vue-i18n-core/test/components/NumberFormat.test.ts
  packages/vue-i18n-core/test/components/Translation.test.ts
  packages/vue-i18n-core/test/composer.test.ts
  packages/vue-i18n-core/test/directive.test.ts
  packages/vue-i18n-core/test/diretive.test.ts
  packages/vue-i18n-core/test/i18n.test.ts
  packages/vue-i18n-core/test/issues.test.ts
  packages/vue-i18n-core/test/legacy.test.ts
  packages/vue-i18n-core/test/mixin.test.ts
  packages/vue-i18n-core/test/ssr.test.ts
  packages/vue-i18n-core/test/wc.test.ts
  packages/vue-i18n/README.md
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/runtime.ts
  rollup.config.mjs
  vitest.config.ts
Labels: Type: Feature, Type: Breaking

#1854 fix: typo in migration breaking changes v10
  docs/guide/migration/breaking10.md
Labels: Type: Documentation

#1860 fix: cannot reduce message-compiler bundle size for runtime
  packages/core-base/src/compilation.ts
  scripts/utils.ts
Labels: Type: Bug

#1863 docs: fix typos
  docs/guide/advanced/sfc.md
  docs/guide/advanced/typescript.md
  docs/guide/essentials/syntax.md
Labels: Type: Documentation

#1864 fix: change repository name
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  BACKERS.md
  README.md
  docs/.ja/ecosystem/official.md
  docs/.ja/guide/advanced/component.md
  docs/.ja/guide/advanced/typescript.md
  docs/.ja/guide/advanced/wc.md
  docs/.ja/guide/migration/vue2.md
  docs/.ja/installation.md
  docs/.ja/v8-docs.md
  docs/.vitepress/config.mts
  docs/ecosystem/official.md
  docs/guide/advanced/component.md
  docs/guide/advanced/format.md
  docs/guide/advanced/lite.md
  docs/guide/advanced/typescript.md
  docs/guide/advanced/wc.md
  docs/guide/extra/v8-docs.md
  docs/guide/integrations/nuxt3.md
  docs/guide/migration/vue2.md
  docs/guide/v8-docs.md
  docs/index.md
  examples/tsx/src/main.ts
  package.json
  packages/core-base/package.json
  packages/core/package.json
  packages/devtools-types/package.json
  packages/format-explorer/src/components/Navigation.vue
  packages/message-compiler/package.json
  packages/petite-vue-i18n/README.md
  packages/petite-vue-i18n/package.json
  packages/shared/package.json
  packages/vue-i18n-core/package.json
  packages/vue-i18n/package.json
Labels: Type: Maintenance
