Repository intlify/vue-i18n, pull requests merged in 2024-03, with the labels that each got.

#1631 chore(fix): #1630 make the install function synchronous to be aligned…
  packages/vue-i18n-core/src/i18n.ts
Labels: Type: Improvement

#1753 docs: wrong te docs
  packages/petite-vue-i18n/src/vue.d.ts
  packages/vue-i18n-bridge/src/vue.d.ts
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Documentation

#1758 chore: introduce eslint flat config
  .eslintignore
  .eslintrc.cjs
  .vscode/settings.json
  benchmark/compile.mjs
  eslint.config.mjs
  package.json
  packages/core-base/src/format.ts
  packages/format-explorer/src/App.vue
  packages/format-explorer/src/components/Navigation.vue
  packages/format-explorer/src/components/Options.vue
  packages/message-compiler/src/helpers.ts
  packages/message-compiler/src/minifier.ts
  packages/message-compiler/src/parser.ts
  packages/message-compiler/src/tokenizer.ts
  packages/message-compiler/src/transformer.ts
  pnpm-lock.yaml
  scripts/api/processor.js
Labels: Type: Maintenance

#1766 fix: manually add triple slash directive to `message-compiler`
  packages/message-compiler/src/generator.ts
Labels: Type: Bug
