Repository intlify/vue-i18n, pull requests merged in 2024-12, with the labels that each got.

#2040 Fix typo
  packages/core-base/src/runtime.ts
Labels: Type: Documentation

#2041 Fix another typo
  packages/core-base/src/runtime.ts
Labels: Type: Documentation

#2044 docs: add maintenance status
  .npmrc
  docs/.vitepress/config.mts
  docs/guide/extra/maintenance.md
  docs/guide/introduction.md
  docs/public/lifecycle2024.excalidraw
  docs/public/lifecycle2024.png
  docs/public/lifecycle2024.svg
  package.json
Labels: Type: Documentation

#2057 fix: v-t custom directive warning when it will run
  packages/vue-i18n-core/src/directive.ts
Labels: Type: Improvement

#2058 feat: reactive `availableLocales` using computed property
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/legacy.ts
  packages/vue-i18n-core/test/composer.test.ts
  packages/vue-i18n-core/test/legacy.test.ts
Labels: Type: Feature, 🍰 p2-nice-to-have

#2059 docs: API reference for multi version preparation
  .gitignore
  docs/.vitepress/config.mts
  docs/api/component.md
  docs/api/composition.md
  docs/api/directive.md
  docs/api/general.md
  docs/api/legacy.md
  docs/api/v11/injection.md
  package.json
  packages/core-base/src/fallbacker.ts
  packages/vue-i18n-core/src/components/DatetimeFormat.ts
  packages/vue-i18n-core/src/components/NumberFormat.ts
  packages/vue-i18n-core/src/components/Translation.ts
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/legacy.ts
Labels: Type: Documentation

#2061 breaking: drop custom directive v-t
  docs/.vitepress/config.mts
  docs/guide/migration/breaking12.md
  e2e/directive/basic.spec.ts
  e2e/directive/object.spec.ts
  e2e/directive/plural.spec.ts
  e2e/directive/preserve.spec.ts
  examples/composition/directive/basic.html
  examples/composition/directive/object.html
  examples/composition/directive/plural.html
  examples/composition/directive/preserve.html
  examples/legacy/directive/basic.html
  examples/legacy/directive/object.html
  examples/legacy/directive/plural.html
  examples/legacy/directive/preserve.html
  packages/devtools-types/src/index.ts
  packages/vue-i18n-core/src/directive.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/index.ts
  packages/vue-i18n-core/src/plugin.ts
  packages/vue-i18n-core/src/plugin/next.ts
  packages/vue-i18n-core/test/directive.test.ts
  packages/vue-i18n-core/test/issues.test.ts
  packages/vue-i18n-core/test/plugin.test.ts
  packages/vue-i18n-core/test/ssr.test.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/runtime.ts
Labels: Type: Breaking
