Repository intlify/vue-i18n, pull requests merged in 2024-09, with the labels that each got.

#1935 fix: type errors
  .github/workflows/ci.yml
  package.json
  packages/core-base/src/index.ts
  packages/core-base/src/runtime.ts
  packages/core-base/src/translate.ts
  packages/core-base/src/types/utils.ts
  packages/core-base/test/context.test-d.ts
  packages/core-base/test/datetime.test-d.ts
  packages/core-base/test/helper.ts
  packages/core-base/test/number.test-d.ts
  packages/core-base/test/runtime.test-d.ts
  packages/core-base/test/schema.ts
  packages/core-base/test/translate.test-d.ts
  packages/core-base/test/translate.test.ts
  packages/core-base/test/types.test-d.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/utils.ts
  packages/vue-i18n-core/test/components/DatetimeFormat.test.ts
  packages/vue-i18n-core/test/components/NumberFormat.test.ts
  packages/vue-i18n-core/test/components/Translation.test.ts
  packages/vue-i18n-core/test/components/components.test-d.tsx
  packages/vue-i18n-core/test/composer.test-d.ts
  packages/vue-i18n-core/test/i18n.test-d.ts
  packages/vue-i18n-core/test/issues.test.ts
  packages/vue-i18n-core/test/legacy.test-d.ts
  packages/vue-i18n-core/test/mixin.test.ts
  packages/vue-i18n-core/test/schema.ts
  pnpm-lock.yaml
  rollup.config.mjs
  test-dts/core-base/context.test-d.ts
  test-dts/core-base/datetime.test-d.ts
  test-dts/core-base/number.test-d.ts
  test-dts/core-base/runtime.test-d.ts
  test-dts/core-base/translate.test-d.ts
  test-dts/index.d.ts
  test-dts/tsconfig.json
  test-dts/vue-i18n/components.test-d.tsx
  test-dts/vue-i18n/composer.test-d.ts
  test-dts/vue-i18n/i18n.test-d.ts
  test-dts/vue-i18n/legacy.test-d.ts
  tsconfig.json
Labels: Type: Improvement

#1941 chore(deps): update `rollup`
  package.json
  packages/core-base/src/context.ts
  packages/core-base/src/resolver.ts
  packages/vue-i18n-core/src/i18n.ts
  pnpm-lock.yaml
  rollup.config.mjs
Labels: Type: Build

#1945 fix: petite-vue-i18n type errors
  packages/petite-vue-i18n/src/vue.d.ts
  scripts/build.ts
Labels: Type: Bug

#1948 chore(deps): update `execa` to v9
  package.json
  packages/format-explorer/vite.config.ts
  pnpm-lock.yaml
  scripts/build.ts
  scripts/dev.ts
Labels: Type: Maintenance

#1951 docs: add team members
  docs/guide/introduction.md
Labels: Type: Documentation

#1964 docs: add how to use shared locale messages on composition api
  .github/workflows/ci.yml
  docs/guide/advanced/composition.md
Labels: Type: Documentation

#1967 fix(petite-vue-i18n): cannot register correctly message resolver and locale fallbacker
  docs/guide/advanced/lite.md
  packages/petite-vue-i18n/src/index.ts
  packages/petite-vue-i18n/src/runtime.ts
Labels: Type: Bug

#1968 docs: add unplugin-vue-i18n setting for petite-vue-i18n
  docs/guide/advanced/lite.md
Labels: Type: Documentation

#1971 Add petite-vue-i18n package to README
  README.md
Labels: Type: Documentation

#1975 fix: vue-i18n type definition for vue package
  packages/shared/src/messages.ts
  packages/shared/test/messages.test.ts
Labels: Type: Bug
