Repository intlify/vue-i18n, pull requests merged in 2024-07, with the labels that each got.

#1883 fix(types): `$t` types
  packages/core-base/src/types/utils.ts
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Bug

#1881 Fix typos, syntax
  docs/guide/advanced/optimization.md
Labels: Type: Documentation

#1885 fix(devtools): change vue-devtools label
  packages/vue-i18n-core/src/devtools.ts
Labels: Type: Improvement

#1888 fix: vue-i18n type definition for vue package
  packages/petite-vue-i18n/src/vue.d.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Improvement

#1890 feat: support generated locale type
  packages/core-base/src/runtime.ts
  packages/petite-vue-i18n/src/index.ts
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/legacy.ts
  packages/vue-i18n/src/index.ts
Labels: Type: Feature

#1897 chore(deps): update dependency vue to v3.4.32
  package.json
  packages/vue-i18n-core/test/__snapshots__/composer.test.ts.snap
  pnpm-lock.yaml
Labels: Type: Maintenance

#1898 chore: fix module augmentation example comment
  packages/core-base/src/runtime.ts
Labels: Type: Documentation

#1899 test: remove duplicate directive test file
  packages/vue-i18n-core/test/diretive.test.ts
Labels: Type: Maintenance
