Repository intlify/vue-i18n, pull requests merged in 2024-01, with the labels that each got.

#1677 fix: lower memory usage
  packages/shared/src/messages.ts
  packages/vue-i18n-core/src/composer.ts
Labels: Type: Performance

#1676 Update installation.md
  docs/guide/installation.md
Labels: Type: Documentation

#1718 fix: key-value style messages broken after merging (#1717)
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/test/issues.test.ts
Labels: Type: Bug, 🔨 p3-minor-bug

#1716 chore(typo): update injection.md
  docs/api/injection.md
Labels: Type: Documentation

#1701 Update syntax.md
  docs/guide/essentials/syntax.md
Labels: Type: Documentation
