Repository intlify/vue-i18n, pull requests merged in 2024-11, with the labels that each got.

#2003 Change config prop for quasar flags
  docs/guide/advanced/optimization.md
Labels: Type: Documentation

#1998 docs: Pluralization Page
  docs/guide/essentials/pluralization.md
Labels: Type: Documentation

#2008 Fix: Composition.md
  docs/guide/advanced/composition.md
Labels: Type: Documentation

#2012 fix(docs): correct output in composition api example
  docs/guide/advanced/composition.md
Labels: Type: Documentation

#2013 docs: not use deprecated api
  docs/.ja/guide/advanced/function.md
  docs/.ja/guide/essentials/pluralization.md
  docs/guide/advanced/function.md
  docs/guide/essentials/pluralization.md
  examples/legacy/functions/plural.html
  examples/legacy/plural/basic.html
  examples/legacy/plural/custom.html
Labels: Type: Documentation

#2014 fix: `tm` function should accept `DefineLocaleMessage` key type
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Improvement

#2016 feat!: deprecate Legacy API mode
  e2e/fallback/basic.spec.ts
  e2e/fallback/format.spec.ts
  e2e/fallback/option.spec.ts
  e2e/fallback/suppress.spec.ts
  e2e/missing/handler.spec.ts
  e2e/missing/option.spec.ts
  e2e/missing/suppress.spec.ts
  package.json
  packages/size-check-petite-vue-i18n/src/main.ts
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/src/i18n.ts
  packages/vue-i18n-core/src/legacy.ts
  packages/vue-i18n-core/src/warnings.ts
  packages/vue-i18n-core/test/directive.test.ts
  packages/vue-i18n-core/test/ssr.test.ts
  pnpm-lock.yaml
Labels: Type: Breaking

#2026 chore: fix not work e2e in local
  .github/workflows/ci.yml
  .github/workflows/release.yml
  package.json
  pnpm-lock.yaml
  scripts/release.sh
  scripts/vitest.globalSetup.ts
Labels: Type: Maintenance

#2027 chore: fix not e2e in local on v9
  package.json
  pnpm-lock.yaml
  scripts/vitest.globalSetup.ts
Labels: Type: Maintenance

#2033 docs: fix wrong plural example
  docs/guide/essentials/pluralization.md
Labels: Type: Documentation

#2034 fix: security vulnerability fix porting
  e2e/hotfix.spec.ts
  e2e/hotfix/CVE-2024-52809.html
  package.json
  packages/core-base/src/compilation.ts
  packages/core-base/src/context.ts
  packages/core-base/src/datetime.ts
  packages/core-base/src/errors.ts
  packages/core-base/src/format.ts
  packages/core-base/src/number.ts
  packages/core-base/src/runtime.ts
  packages/core-base/src/translate.ts
  packages/core-base/test/format.test.ts
  packages/core-base/test/issues.test.ts
  packages/message-compiler/src/tokenizer.ts
  packages/shared/src/messages.ts
  packages/shared/src/utils.ts
  packages/shared/test/messages.test.ts
  packages/vue-i18n-core/src/components/DatetimeFormat.ts
  packages/vue-i18n-core/src/components/NumberFormat.ts
  packages/vue-i18n-core/src/components/Translation.ts
  packages/vue-i18n-core/src/components/base.ts
  packages/vue-i18n-core/src/components/formatRenderer.ts
  packages/vue-i18n-core/src/components/index.ts
  packages/vue-i18n-core/src/components/utils.ts
  packages/vue-i18n-core/src/utils.ts
  packages/vue-i18n-core/test/issues.test.ts
  pnpm-lock.yaml
  scripts/vitest.globalSetup.ts
Labels: Type: Security

#2036 test: use random available port for `e2e` tests
  e2e/components/datetime-format.spec.ts
  e2e/components/number-format.spec.ts
  e2e/components/translation.spec.ts
  e2e/datetime.spec.ts
  e2e/directive/basic.spec.ts
  e2e/directive/object.spec.ts
  e2e/directive/plural.spec.ts
  e2e/directive/preserve.spec.ts
  e2e/fallback/basic.spec.ts
  e2e/fallback/component.spec.ts
  e2e/fallback/default-format.spec.ts
  e2e/fallback/format.spec.ts
  e2e/fallback/option.spec.ts
  e2e/fallback/suppress.spec.ts
  e2e/formatting/linked.spec.ts
  e2e/formatting/list.spec.ts
  e2e/formatting/literal.spec.ts
  e2e/formatting/named.spec.ts
  e2e/functions/linked.spec.ts
  e2e/functions/list.spec.ts
  e2e/functions/named.spec.ts
  e2e/functions/plural.spec.ts
  e2e/helper.ts
  e2e/hotfix.spec.ts
  e2e/missing/handler.spec.ts
  e2e/missing/option.spec.ts
  e2e/missing/suppress.spec.ts
  e2e/number.spec.ts
  e2e/plural/basic.spec.ts
  e2e/plural/custom.spec.ts
  e2e/scope/global.spec.ts
  e2e/scope/inherit-locale.spec.ts
  e2e/scope/local.spec.ts
  e2e/started.spec.ts
  package.json
  pnpm-lock.yaml
  scripts/test-utils.ts
  scripts/vitest.globalSetup.ts
Labels: Type: Maintenance

#2038 docx(pluralization.md): Correct spelling from 'gloal' to 'global'
  docs/guide/essentials/pluralization.md
Labels: Type: Documentation
