Repository intlify/vue-i18n, pull requests merged in 2025-04, with the labels that each got.

#2151 Fix typos in CHANGELOG
  CHANGELOG.md
Labels: Type: Documentation

#2157 fix: cannot resolve the ast messages which has json path
  packages/core-base/src/ast.ts
  packages/core-base/src/compilation.ts
  packages/core-base/src/format.ts
  packages/core-base/src/index.ts
  packages/core-base/src/resolver.ts
  packages/core-base/src/translate.ts
  packages/core-base/test/compilation.test.ts
  packages/core-base/test/fixtures/ast.ts
  packages/core-base/test/resolver.test.ts
  packages/core-base/test/translate.test.ts
  packages/vue-i18n-core/src/utils.ts
  packages/vue-i18n-core/test/fixtures/ast.ts
  packages/vue-i18n-core/test/issues.test.ts
  packages/vue-i18n-core/test/utils.test.ts
Labels: Type: Bug

#2158 fix: duplicate generated type config naming
  packages/vue-i18n-core/src/types.ts
Labels: Type: Improvement

#2159 fix: cannot resolve the ast messages which has json path for v11
  packages/core-base/src/ast.ts
  packages/core-base/src/compilation.ts
  packages/core-base/src/format.ts
  packages/core-base/src/index.ts
  packages/core-base/src/resolver.ts
  packages/core-base/src/translate.ts
  packages/core-base/test/compilation.test.ts
  packages/core-base/test/fixtures/ast.ts
  packages/core-base/test/resolver.test.ts
  packages/core-base/test/translate.test.ts
  packages/vue-i18n-core/src/utils.ts
  packages/vue-i18n-core/test/fixtures/ast.ts
  packages/vue-i18n-core/test/issues.test.ts
  packages/vue-i18n-core/test/utils.test.ts
Labels: Type: Bug

#2160 fix: cannot resolve the ast messages which has json path for v10
  packages/core-base/src/ast.ts
  packages/core-base/src/compilation.ts
  packages/core-base/src/format.ts
  packages/core-base/src/index.ts
  packages/core-base/src/resolver.ts
  packages/core-base/src/translate.ts
  packages/core-base/test/compilation.test.ts
  packages/core-base/test/fixtures/ast.ts
  packages/core-base/test/resolver.test.ts
  packages/core-base/test/translate.test.ts
  packages/vue-i18n-core/src/utils.ts
  packages/vue-i18n-core/test/fixtures/ast.ts
  packages/vue-i18n-core/test/issues.test.ts
  packages/vue-i18n-core/test/utils.test.ts
Labels: Type: Bug

#2162 fix: cannot resolve the ast messages which has json path for v9
  e2e/bridge/basic.spec.ts
  e2e/bridge/component.spec.ts
  e2e/bridge/components/datetime-format.spec.ts
  e2e/bridge/components/number-format.spec.ts
  e2e/bridge/components/translation.spec.ts
  e2e/bridge/plural.spec.ts
  e2e/bridge/scope/global.spec.ts
  e2e/bridge/scope/inherit-locale.spec.ts
  e2e/bridge/scope/local.spec.ts
  packages/core-base/src/ast.ts
  packages/core-base/src/compilation.ts
  packages/core-base/src/format.ts
  packages/core-base/src/index.ts
  packages/core-base/src/resolver.ts
  packages/core-base/src/translate.ts
  packages/core-base/test/compilation.test.ts
  packages/core-base/test/fixtures/ast.ts
  packages/core-base/test/resolver.test.ts
  packages/core-base/test/translate.test.ts
  packages/vue-i18n-core/src/utils.ts
  packages/vue-i18n-core/test/fixtures/ast.ts
  packages/vue-i18n-core/test/issues.test.ts
  packages/vue-i18n-core/test/utils.test.ts
Labels: Type: Bug

#2167 fix: update slot key filtering to exclude internal keys
  packages/vue-i18n-core/src/components/Translation.ts
Labels: Type: Improvement

#2168 docs: llms friendly text generation
  docs/.vitepress/config.mts
  package.json
  pnpm-lock.yaml
Labels: Type: Documentation

#2170 Part options support for $n
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/test/composer.test-d.ts
  packages/vue-i18n-core/test/composer.test.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Feature

#2173 examples: Storybook Example with vue3 and vite
  examples/storybook/.editorconfig
  examples/storybook/.gitattributes
  examples/storybook/.gitignore
  examples/storybook/.prettierrc.json
  examples/storybook/.storybook/main.ts
  examples/storybook/.storybook/preview.ts
  examples/storybook/README.md
  examples/storybook/env.d.ts
  examples/storybook/eslint.config.ts
  examples/storybook/index.html
  examples/storybook/package.json
  examples/storybook/public/favicon.ico
  examples/storybook/src/App.vue
  examples/storybook/src/assets/base.css
  examples/storybook/src/assets/logo.svg
  examples/storybook/src/assets/main.css
  examples/storybook/src/components/HelloWorld.vue
  examples/storybook/src/components/TheWelcome.vue
  examples/storybook/src/components/WelcomeItem.vue
  examples/storybook/src/components/icons/IconCommunity.vue
  examples/storybook/src/components/icons/IconDocumentation.vue
  examples/storybook/src/components/icons/IconEcosystem.vue
  examples/storybook/src/components/icons/IconSupport.vue
  examples/storybook/src/components/icons/IconTooling.vue
  examples/storybook/src/locales/en.json
  examples/storybook/src/locales/fr.json
  examples/storybook/src/main.ts
  examples/storybook/src/stories/Button.stories.ts
  examples/storybook/src/stories/Button.vue
  examples/storybook/src/stories/Header.stories.ts
  examples/storybook/src/stories/Header.vue
  examples/storybook/src/stories/LocalizedPage.stories.ts
  examples/storybook/src/stories/LocalizedPage.vue
  examples/storybook/src/stories/Page.stories.ts
  examples/storybook/src/stories/Page.vue
  examples/storybook/src/stories/button.css
  examples/storybook/src/stories/header.css
  examples/storybook/src/stories/page.css
  examples/storybook/tsconfig.app.json
  examples/storybook/tsconfig.json
  examples/storybook/tsconfig.node.json
  examples/storybook/vite.config.ts
  pnpm-lock.yaml
Labels: Type: Example

#2174 fix: improvement `n` and `$n` typings
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/test/composer.test-d.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Improvement

#2176 breaking: update component injection APIs for drop legacy
  packages/petite-vue-i18n/src/vue.d.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Breaking

#2175 Part options support $n - v11
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/test/composer.test-d.ts
  packages/vue-i18n-core/test/composer.test.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Feature
