Repository intlify/vue-i18n, pull requests merged in 2025-02, with the labels that each got.

#2095 Update introduction.md
  docs/guide/introduction.md
Labels: Type: Documentation

#2104 Fix: Synchronous Watcher Issue Caused by Locale Setting Order
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/test/composer.test.ts
Labels: Type: Bug

#2109 drop node v18
  .github/workflows/ci.yml
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  package.json
Labels: Type: Breaking

#2111 Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: Type: Documentation

#2116 remove docs/.ja
  docs/.ja/api/component.md
  docs/.ja/api/composition.md
  docs/.ja/api/directive.md
  docs/.ja/api/general.md
  docs/.ja/api/injection.md
  docs/.ja/api/legacy.md
  docs/.ja/ecosystem/integrations.md
  docs/.ja/ecosystem/official.md
  docs/.ja/ecosystem/tools.md
  docs/.ja/guide/advanced/component.md
  docs/.ja/guide/advanced/composition.md
  docs/.ja/guide/advanced/directive.md
  docs/.ja/guide/advanced/function.md
  docs/.ja/guide/advanced/lazy.md
  docs/.ja/guide/advanced/optimization.md
  docs/.ja/guide/advanced/sfc.md
  docs/.ja/guide/advanced/typescript.md
  docs/.ja/guide/advanced/wc.md
  docs/.ja/guide/essentials/datetime.md
  docs/.ja/guide/essentials/fallback.md
  docs/.ja/guide/essentials/local.md
  docs/.ja/guide/essentials/number.md
  docs/.ja/guide/essentials/pluralization.md
  docs/.ja/guide/essentials/scope.md
  docs/.ja/guide/essentials/syntax.md
  docs/.ja/guide/index.md
  docs/.ja/guide/migration/breaking.md
  docs/.ja/guide/migration/features.md
  docs/.ja/guide/migration/vue2.md
  docs/.ja/guide/migration/vue3.md
  docs/.ja/index.md
  docs/.ja/installation.md
  docs/.ja/introduction.md
  docs/.ja/v8-docs.md
Labels: Type: Maintenance

#2112 ship ESM only
  .github/CONTRIBUTING.md
  docs/guide/extra/dist.md
  eslint.config.mjs
  packages/core-base/index.js
  packages/core-base/package.json
  packages/core/README.md
  packages/core/index.js
  packages/core/package.json
  packages/devtools-types/index.js
  packages/devtools-types/package.json
  packages/message-compiler/index.js
  packages/message-compiler/package.json
  packages/petite-vue-i18n/index.js
  packages/petite-vue-i18n/package.json
  packages/shared/index.js
  packages/shared/package.json
  packages/vue-i18n-core/index.js
  packages/vue-i18n-core/package.json
  packages/vue-i18n-core/petite.js
  packages/vue-i18n/README.md
  packages/vue-i18n/index.js
  packages/vue-i18n/package.json
  rollup.config.mjs
  scripts/build-rolldown.ts
  scripts/build.ts
  scripts/dev.ts
  scripts/rolldown.ts
  scripts/utils.ts
Labels: Type: Breaking
