Repository intlify/vue-i18n, pull requests merged in 2025-05, with the labels that each got.

#2177 feat: Part options support $d
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/test/composer.test-d.ts
  packages/vue-i18n-core/test/composer.test.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Feature

#2180 feat: Part options support $d
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/test/composer.test-d.ts
  packages/vue-i18n-core/test/composer.test.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Feature

#2190 fix: support vue core internal slot key changing
  packages/vue-i18n-core/src/components/Translation.ts
  packages/vue-i18n-core/test/components/Translation.test.ts
  pnpm-lock.yaml
Labels: Type: Improvement

#2186 Named, list, modifier examples
  docs/guide/essentials/syntax.md
  packages/vue-i18n-core/test/composer.test.ts
Labels: Type: Improvement, 🍰 p2-nice-to-have

#2194 fix: n() & d() output depending "part" option
  packages/vue-i18n-core/src/composer.ts
  packages/vue-i18n-core/test/composer.test-d.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Bug
