Repository intlify/vue-i18n, pull requests merged in 2025-01, with the labels that each got.

#2062 refactor: build and dev scripts
  package.json
  pnpm-lock.yaml
  scripts/build.sh
  scripts/build.ts
  scripts/dev.ts
  scripts/utils.ts
Labels: Type: Maintenance

#2064 feat!: change to `mangle` option name from `minify` option name
  .github/workflows/size-report.yml
  packages/core-base/test/compilation.test.ts
  packages/message-compiler/src/compiler.ts
  packages/message-compiler/src/mangler.ts
  packages/message-compiler/src/options.ts
  packages/message-compiler/test/__snapshots__/compiler.test.ts.snap
  packages/message-compiler/test/__snapshots__/mangler.test.ts.snap
  packages/message-compiler/test/compiler.test.ts
  packages/message-compiler/test/mangler.test.ts
Labels: Type: Breaking

#2081 fix(installation.md): update installation commands for package manager
  docs/guide/installation.md
Labels: Type: Documentation

#2094 feat: configurable `ComponentCustomProperties['$i18n']` type
  packages/vue-i18n-core/src/index.ts
  packages/vue-i18n-core/src/types.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Feature

#2093 feat: configurable `ComponentCustomProperties['$i18n']` type
  packages/vue-i18n-core/src/index.ts
  packages/vue-i18n-core/src/types.ts
  packages/vue-i18n/src/index.ts
  packages/vue-i18n/src/vue.d.ts
Labels: Type: Feature
